version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    allow:
      - dependency-name: aquasecurity/trivy-action
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "release:internal"
    open-pull-requests-limit: 10
