services:
  db:
    volumes: []

  backend:
    restart: "no"
    command: ["npm", "run", "start"]
    volumes: []
    environment:
      CHOKIDAR_USEPOLLING: "false"

  frontend:
    restart: "no"
    volumes: []
