apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-git-repos
  labels:
    app.kubernetes.io/name: enterpriseglue-backend
    app.kubernetes.io/part-of: enterpriseglue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
