import { z } from 'zod';

// Historic task schemas (API-only, no DB persistence)
export const HistoricTaskInstanceSchema = z.object({
  id: z.string(),
  processDefinitionKey: z.string().optional().nullable(),
  processDefinitionId: z.string().optional().nullable(),
  processInstanceId: z.string().optional().nullable(),
  executionId: z.string().optional().nullable(),
  caseDefinitionKey: z.string().optional().nullable(),
  caseDefinitionId: z.string().optional().nullable(),
  caseInstanceId: z.string().optional().nullable(),
  caseExecutionId: z.string().optional().nullable(),
  activityInstanceId: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  deleteReason: z.string().optional().nullable(),
  owner: z.string().optional().nullable(),
  assignee: z.string().optional().nullable(),
  startTime: z.string().optional().nullable(),
  endTime: z.string().optional().nullable(),
  duration: z.number().optional().nullable(),
  taskDefinitionKey: z.string().optional().nullable(),
  priority: z.number().optional().nullable(),
  due: z.string().optional().nullable(),
  parentTaskId: z.string().optional().nullable(),
  followUp: z.string().optional().nullable(),
  tenantId: z.string().optional().nullable(),
  removalTime: z.string().optional().nullable(),
  rootProcessInstanceId: z.string().optional().nullable(),
});

// Historic variable instance schemas
export const HistoricVariableInstanceSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  value: z.any(),
  processDefinitionKey: z.string().optional().nullable(),
  processDefinitionId: z.string().optional().nullable(),
  processInstanceId: z.string().optional().nullable(),
  executionId: z.string().optional().nullable(),
  activityInstanceId: z.string().optional().nullable(),
  caseDefinitionKey: z.string().optional().nullable(),
  caseDefinitionId: z.string().optional().nullable(),
  caseInstanceId: z.string().optional().nullable(),
  caseExecutionId: z.string().optional().nullable(),
  taskId: z.string().optional().nullable(),
  tenantId: z.string().optional().nullable(),
  errorMessage: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  createTime: z.string().optional().nullable(),
  removalTime: z.string().optional().nullable(),
  rootProcessInstanceId: z.string().optional().nullable(),
});

// Historic decision instance schemas
export const HistoricDecisionInstanceSchema = z.object({
  id: z.string(),
  decisionDefinitionId: z.string().optional().nullable(),
  decisionDefinitionKey: z.string().optional().nullable(),
  decisionDefinitionName: z.string().optional().nullable(),
  processDefinitionKey: z.string().optional().nullable(),
  processDefinitionId: z.string().optional().nullable(),
  processInstanceId: z.string().optional().nullable(),
  caseDefinitionKey: z.string().optional().nullable(),
  caseDefinitionId: z.string().optional().nullable(),
  caseInstanceId: z.string().optional().nullable(),
  activityId: z.string().optional().nullable(),
  activityInstanceId: z.string().optional().nullable(),
  evaluationTime: z.string().optional().nullable(),
  removalTime: z.string().optional().nullable(),
  userId: z.string().optional().nullable(),
  rootDecisionInstanceId: z.string().optional().nullable(),
  rootProcessInstanceId: z.string().optional().nullable(),
  decisionRequirementsDefinitionId: z.string().optional().nullable(),
  decisionRequirementsDefinitionKey: z.string().optional().nullable(),
  tenantId: z.string().optional().nullable(),
});

// User operation log schemas
export const UserOperationLogEntrySchema = z.object({
  id: z.string(),
  userId: z.string().optional().nullable(),
  timestamp: z.string().optional().nullable(),
  operationId: z.string().optional().nullable(),
  operationType: z.string().optional().nullable(),
  entityType: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  annotation: z.string().optional().nullable(),
  property: z.string().optional().nullable(),
  orgValue: z.string().optional().nullable(),
  newValue: z.string().optional().nullable(),
  deploymentId: z.string().optional().nullable(),
  processDefinitionId: z.string().optional().nullable(),
  processDefinitionKey: z.string().optional().nullable(),
  processInstanceId: z.string().optional().nullable(),
  executionId: z.string().optional().nullable(),
  caseDefinitionId: z.string().optional().nullable(),
  caseInstanceId: z.string().optional().nullable(),
  caseExecutionId: z.string().optional().nullable(),
  taskId: z.string().optional().nullable(),
  externalTaskId: z.string().optional().nullable(),
  batchId: z.string().optional().nullable(),
  jobId: z.string().optional().nullable(),
  jobDefinitionId: z.string().optional().nullable(),
  removalTime: z.string().optional().nullable(),
  rootProcessInstanceId: z.string().optional().nullable(),
});

// Query params
export const HistoricTaskQueryParams = z.object({
  taskId: z.string().optional(),
  processDefinitionId: z.string().optional(),
  processDefinitionKey: z.string().optional(),
  processInstanceId: z.string().optional(),
  processInstanceBusinessKey: z.string().optional(),
  executionId: z.string().optional(),
  activityInstanceIdIn: z.array(z.string()).optional(),
  taskDefinitionKey: z.string().optional(),
  taskDefinitionKeyIn: z.array(z.string()).optional(),
  taskName: z.string().optional(),
  taskNameLike: z.string().optional(),
  taskDescription: z.string().optional(),
  taskDescriptionLike: z.string().optional(),
  taskDeleteReason: z.string().optional(),
  taskDeleteReasonLike: z.string().optional(),
  taskAssignee: z.string().optional(),
  taskAssigneeLike: z.string().optional(),
  taskOwner: z.string().optional(),
  taskOwnerLike: z.string().optional(),
  taskPriority: z.number().optional(),
  assigned: z.boolean().optional(),
  unassigned: z.boolean().optional(),
  finished: z.boolean().optional(),
  unfinished: z.boolean().optional(),
  processFinished: z.boolean().optional(),
  processUnfinished: z.boolean().optional(),
  taskDueDate: z.string().optional(),
  taskDueDateBefore: z.string().optional(),
  taskDueDateAfter: z.string().optional(),
  taskFollowUpDate: z.string().optional(),
  taskFollowUpDateBefore: z.string().optional(),
  taskFollowUpDateAfter: z.string().optional(),
  startedBefore: z.string().optional(),
  startedAfter: z.string().optional(),
  finishedBefore: z.string().optional(),
  finishedAfter: z.string().optional(),
  tenantIdIn: z.array(z.string()).optional(),
  withoutTenantId: z.boolean().optional(),
  sortBy: z.enum(['taskId', 'activityInstanceId', 'processDefinitionId', 'processInstanceId', 'executionId', 'duration', 'endTime', 'startTime', 'taskName', 'taskDescription', 'assignee', 'owner', 'dueDate', 'followUpDate', 'deleteReason', 'taskDefinitionKey', 'priority', 'tenantId']).optional(),
  sortOrder: z.enum(['asc', 'desc']).optional(),
  firstResult: z.number().optional(),
  maxResults: z.number().optional(),
});

export const HistoricVariableQueryParams = z.object({
  variableName: z.string().optional(),
  variableNameLike: z.string().optional(),
  variableValue: z.any().optional(),
  variableTypeIn: z.array(z.string()).optional(),
  processInstanceId: z.string().optional(),
  processInstanceIdIn: z.array(z.string()).optional(),
  processDefinitionId: z.string().optional(),
  processDefinitionKey: z.string().optional(),
  executionIdIn: z.array(z.string()).optional(),
  caseInstanceId: z.string().optional(),
  caseExecutionIdIn: z.array(z.string()).optional(),
  caseActivityIdIn: z.array(z.string()).optional(),
  taskIdIn: z.array(z.string()).optional(),
  activityInstanceIdIn: z.array(z.string()).optional(),
  tenantIdIn: z.array(z.string()).optional(),
  withoutTenantId: z.boolean().optional(),
  sortBy: z.enum(['instanceId', 'variableName', 'tenantId']).optional(),
  sortOrder: z.enum(['asc', 'desc']).optional(),
  firstResult: z.number().optional(),
  maxResults: z.number().optional(),
});

export const HistoricDecisionQueryParams = z.object({
  decisionInstanceId: z.string().optional(),
  decisionInstanceIdIn: z.array(z.string()).optional(),
  decisionDefinitionId: z.string().optional(),
  decisionDefinitionIdIn: z.array(z.string()).optional(),
  decisionDefinitionKey: z.string().optional(),
  decisionDefinitionKeyIn: z.array(z.string()).optional(),
  decisionDefinitionName: z.string().optional(),
  decisionDefinitionNameLike: z.string().optional(),
  processDefinitionId: z.string().optional(),
  processDefinitionKey: z.string().optional(),
  processInstanceId: z.string().optional(),
  caseDefinitionId: z.string().optional(),
  caseDefinitionKey: z.string().optional(),
  caseInstanceId: z.string().optional(),
  activityIdIn: z.array(z.string()).optional(),
  activityInstanceIdIn: z.array(z.string()).optional(),
  evaluatedBefore: z.string().optional(),
  evaluatedAfter: z.string().optional(),
  userId: z.string().optional(),
  rootDecisionInstanceId: z.string().optional(),
  rootDecisionInstancesOnly: z.coerce.boolean().optional(),
  decisionRequirementsDefinitionId: z.string().optional(),
  decisionRequirementsDefinitionKey: z.string().optional(),
  tenantIdIn: z.array(z.string()).optional(),
  withoutTenantId: z.boolean().optional(),
  sortBy: z.enum(['evaluationTime', 'tenantId']).optional(),
  sortOrder: z.enum(['asc', 'desc']).optional(),
  firstResult: z.coerce.number().optional(),
  maxResults: z.coerce.number().optional(),
});

export const UserOperationLogQueryParams = z.object({
  deploymentId: z.string().optional(),
  processDefinitionId: z.string().optional(),
  processDefinitionKey: z.string().optional(),
  processInstanceId: z.string().optional(),
  executionId: z.string().optional(),
  caseDefinitionId: z.string().optional(),
  caseInstanceId: z.string().optional(),
  caseExecutionId: z.string().optional(),
  taskId: z.string().optional(),
  externalTaskId: z.string().optional(),
  batchId: z.string().optional(),
  jobId: z.string().optional(),
  jobDefinitionId: z.string().optional(),
  userId: z.string().optional(),
  operationId: z.string().optional(),
  operationType: z.string().optional(),
  entityType: z.string().optional(),
  entityTypeIn: z.array(z.string()).optional(),
  category: z.string().optional(),
  categoryIn: z.array(z.string()).optional(),
  property: z.string().optional(),
  afterTimestamp: z.string().optional(),
  beforeTimestamp: z.string().optional(),
  sortBy: z.enum(['timestamp']).optional(),
  sortOrder: z.enum(['asc', 'desc']).optional(),
  firstResult: z.number().optional(),
  maxResults: z.number().optional(),
});

// Types
export type HistoricTaskInstance = z.infer<typeof HistoricTaskInstanceSchema>;
export type HistoricVariableInstance = z.infer<typeof HistoricVariableInstanceSchema>;
export type HistoricDecisionInstance = z.infer<typeof HistoricDecisionInstanceSchema>;
export type UserOperationLogEntry = z.infer<typeof UserOperationLogEntrySchema>;
export type HistoricTaskQueryParams = z.infer<typeof HistoricTaskQueryParams>;
export type HistoricVariableQueryParams = z.infer<typeof HistoricVariableQueryParams>;
export type HistoricDecisionQueryParams = z.infer<typeof HistoricDecisionQueryParams>;
export type UserOperationLogQueryParams = z.infer<typeof UserOperationLogQueryParams>;
