{{- if .Values.podDisruptionBudget.enabled }}
{{- range $component := list "frontend" "api" "worker" }}
{{- if or (ne $component "worker") $.Values.workers.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "enterpriseglue-host.fullname" $ }}-{{ $component }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "enterpriseglue-host.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "enterpriseglue-host.selectorLabels" (dict "root" $ "component" $component) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}

