apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterpriseglue-host.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterpriseglue-host.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "enterpriseglue-host.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterpriseglue-host.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterpriseglue-host.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "enterpriseglue-host.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http

