{{- range $plugin := .Values.pluginRuntime.plugins }}
{{- $context := dict "root" $ "plugin" $plugin }}
{{- include "enterpriseglue-plugin-runtime.validate" $context }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enterpriseglue-plugin-runtime.fullname" $context }}
  labels:
    {{- include "enterpriseglue-plugin-runtime.labels" $context | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
