apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enterpriseglue-plugin-manager-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterpriseglue-plugin-manager
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: enterpriseglue-plugin-manager
  policyTypes: ["Ingress"]
  ingress: []
