apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enterpriseglue-plugin-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterpriseglue-plugin-manager
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.state.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.state.size }}
