apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  labels:
    app.kubernetes.io/name: enterpriseglue
    app.kubernetes.io/part-of: enterpriseglue
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "<base64-encoded-docker-config-json>"
