import type { AuthzActionDefinition } from '../permission-actions.js';

export const ENGINE_AUTHZ_ACTIONS = [
  {
      actionId: 'mission-control.bridge.starbase-edit.evaluate',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'evaluate',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Bridge',
      description: 'Evaluate whether a Mission Control runtime artifact can open the matching Starbase file for editing.',
      ui: [{ surfaceId: 'mission-control.bridge.starbase-edit', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/api/mission-control/bridge/starbase-edit/evaluate',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'project:files:view and project:files:edit are required on the resolved Starbase project',
            'an active project-engine target must connect the resolved project and engine',
            'runtime edit-target lineage must resolve to the requested Starbase file',
          ],
        },
      ],
    },
  {
      actionId: 'engine.deploy.create',
      permissionId: 'engine:deploy',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Deployments',
      description: 'Deploy to an engine.',
      ui: [{ surfaceId: 'engine.deploy.button', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/engines-api/engines/:engineId/deployments', resourceResolver: 'engine.byId' },
        {
          method: 'POST',
          route: '/api/engines/:engineId/deployments',
          resourceResolver: 'engine.byId',
          openApi: false,
          additionalChecks: ['planned canonical engine deploy route; current public route is engines-api'],
        },
      ],
    },
  {
      actionId: 'engine.deployments.read',
      permissionId: 'engine:deploy:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Deployments',
      description: 'Read deployment records and deployment detail from an engine.',
      ui: [{ surfaceId: 'engine.deployments.list', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/starbase-api/deployments', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/starbase-api/deployments/{id}', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/starbase-api/process-definitions/{id}/diagram', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/engines-api/engines/{engineId}/deployments', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/engines-api/engines/{engineId}/deployments/{id}', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/engines-api/engines/{engineId}/deployment-receipts', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/engines-api/engines/{engineId}/deployment-history', resourceResolver: 'engine.byId' },
        { method: 'GET', route: '/engines-api/engines/{engineId}/deployments/{deploymentId}/lineage', resourceResolver: 'engine.byId' },
      ],
    },
  {
      actionId: 'engine.deployments.delete',
      permissionId: 'engine:deploy',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Deployments',
      description: 'Delete a deployment record from an engine.',
      ui: [{ surfaceId: 'engine.deployments.delete', behavior: 'disable' }],
      routes: [
        { method: 'DELETE', route: '/starbase-api/deployments/{id}', resourceResolver: 'engine.byId' },
        { method: 'DELETE', route: '/engines-api/engines/{engineId}/deployments/{id}', resourceResolver: 'engine.byId' },
      ],
    },
  {
      actionId: 'engine.deployment-receipts.create',
      permissionId: 'engine:deploy',
      resourceType: 'engine',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Deployments',
      description: 'Record an externally completed deployment receipt and its sanitized runtime resource lineage.',
      ui: [{ surfaceId: 'engine.deployment-receipts.ingest', behavior: 'disable', coverage: 'api-only' }],
      routes: [{
        method: 'POST',
        route: '/engines-api/external/engines/{engineId}/deployment-receipts',
        resourceResolver: 'projectEngineTarget.fromProjectAndEngine',
        additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'target.mode.api', 'api-client.deployment.execute'],
      }],
    },
  {
      actionId: 'engine.inventory.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Engine Inventory',
      description: 'Read engine inventory rows, engine details, and health state visible to the current user.',
      ui: [
        { surfaceId: 'engines.list', behavior: 'hide' },
        { surfaceId: 'engines.detail', behavior: 'hide' },
        { surfaceId: 'mission-control.engine-selector', behavior: 'hide' },
      ],
      routes: [
        {
          method: 'GET',
          route: '/engines-api/engines',
          resourceResolver: 'engine.visibleCollection',
          additionalChecks: [
            'collection is filtered to engines returned by engineService.getUserEngines',
            'secret-backed fields are redacted unless the user has engine:secrets:view; engine:secrets:manage implies view',
          ],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engine:edit, engine:delete, engine:members:view, engine:members:manage, or legacy engine view role also accepted for compatibility',
            'secret-backed fields are redacted unless the user has engine:secrets:view; engine:secrets:manage implies view',
          ],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{id}/health',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engine:edit, engine:delete, engine:members:view, engine:members:manage, or legacy engine view role also accepted for compatibility',
            'the special __env__ id returns environment health for authenticated users without resolving an engine row',
          ],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{id}/runtime-resources',
          resourceResolver: 'engine.byId',
          additionalChecks: ['returns only sanitized runtime-inventory rows in the caller tenant'],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{id}/tenancy/diagnostics',
          resourceResolver: 'engine.byId',
          additionalChecks: ['returns aggregate sanitized mapping state without credentials or raw tenant claims'],
        },
      ],
    },
  {
      actionId: 'engine.inventory.create',
      permissionId: 'platform:engine:create',
      resourceType: 'platform',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Engine Inventory',
      description: 'Create a manually managed engine record.',
      ui: [{ surfaceId: 'engines.create', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines',
          resourceResolver: 'platform.self',
          additionalChecks: [
            'current handler accepts authenticated users and assigns the caller as owner',
            'future strict enforcement should use platform:engine:create; default user/developer roles include it for compatibility',
            'externalId and label changes refresh Engine Set materializations',
          ],
        },
      ],
    },
  {
      actionId: 'engine.tenancy.classification.read',
      permissionId: 'platform:engine:create',
      resourceType: 'platform',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Engine Inventory',
      description: 'Read the cross-engine tenancy migration classification report.',
      ui: [{ surfaceId: 'engines.tenancy.classification', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/engines-api/engines/tenancy/classification-report',
          resourceResolver: 'platform.self',
          additionalChecks: [
            'report contains sanitized topology state and migration recommendations only',
            'ambiguous resource-aware engines are never inferred as shared or default-tenant dedicated',
          ],
        },
      ],
    },
  {
      actionId: 'engine.external-registration.upsert',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'platform',
      operation: 'sync',
      risk: 'critical',
      audit: true,
      category: 'Engine Inventory',
      description: 'Register or update an engine through the external registration API.',
      ui: [{ surfaceId: 'admin.engine-registration.external-api', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/external/engines',
          resourceResolver: 'platform.self',
          additionalChecks: [
            'API client bearer token with engine:register scope is required',
            'API client must have either platform:engine-registration:manage at platform scope or external-engine-system:engine-registration:manage for the provided externalSystemId',
            'external registration rejects local, private, link-local, reserved, and credential-bearing URLs',
            'Engine Set materializations refresh after create or update',
          ],
        },
        {
          method: 'PUT',
          route: '/engines-api/external/engines/{externalId}/tenant-mappings',
          resourceResolver: 'platform.self',
          additionalChecks: [
            'API client bearer token with engine:register scope is required',
            'every tenant reference requires an authorized resolution',
            'mapping changes are atomic and mapping-version guarded',
          ],
        },
      ],
    },
  {
      actionId: 'engine.external-registration.decommission',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'platform',
      operation: 'sync',
      risk: 'critical',
      audit: true,
      category: 'Engine Inventory',
      description: 'Mark an externally registered engine as decommissioned without deleting its audit or inventory record.',
      ui: [{ surfaceId: 'admin.engine-registration.external-api.decommission', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/external/engines/decommission',
          resourceResolver: 'platform.self',
          additionalChecks: [
            'API client bearer token with engine:register scope is required',
            'API client must have either platform:engine-registration:manage at platform scope or external-engine-system:engine-registration:manage for the provided externalSystemId',
            'only externally registered engines can be decommissioned through this API',
            'decommission keeps engine inventory and audit records but removes Engine Set materializations for the engine',
          ],
        },
      ],
    },
  {
      actionId: 'engine.inventory.update',
      permissionId: 'engine:edit',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Engine Inventory',
      description: 'Update engine configuration or test an engine connection.',
      ui: [{ surfaceId: 'engines.edit', behavior: 'disable' }],
      routes: [
        {
          method: 'PUT',
          route: '/engines-api/engines/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'non-secret inventory fields require engine:edit',
            'authentication and credential fields require engine:secrets:manage',
            'externally registered engines reject source-owned field updates',
          ],
        },
        {
          method: 'POST',
          route: '/engines-api/engines/{id}/test',
          resourceResolver: 'engine.byId',
          additionalChecks: ['legacy engine manage role also accepted for compatibility'],
        },
        {
          method: 'POST',
          route: '/engines-api/engines/{id}/runtime-resources/reconcile',
          resourceResolver: 'engine.byId',
          additionalChecks: ['runs idempotent runtime and deployment metadata discovery with Runtime Resource Set rematerialization'],
        },
        {
          method: 'POST',
          route: '/engines-api/engines/{id}/tenancy/preview',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engine:edit is required for an owned engine',
            'platform:engine-registration:manage is accepted only for an unowned dedicated engine quarantined as migration_required',
            'the migration permission does not make the engine tenant-visible or grant runtime access',
            'externally and configuration-owned topology cannot be changed manually',
            'preview is bounded, expiring, and fingerprinted over affected state',
          ],
        },
        {
          method: 'POST',
          route: '/engines-api/engines/{id}/tenancy/apply',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engine:edit is required for an owned engine',
            'platform:engine-registration:manage is accepted only for an unowned dedicated engine quarantined as migration_required',
            'the migration permission does not make the engine tenant-visible or grant runtime access',
            'matching unexpired preview hash and every required acknowledgement are mandatory',
            'engine, mappings, runtime inventory, and materialization invalidation are applied atomically',
          ],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{id}/tenant-mappings',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:edit is required because mapping rows contain tenant ownership identifiers'],
        },
        {
          method: 'PUT',
          route: '/engines-api/engines/{id}/tenant-mappings',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engine:edit is required',
            'every tenant reference requires an authorized resolution',
            'mapping changes are atomic and mapping-version guarded',
          ],
        },
      ],
    },
  {
      actionId: 'engine.secrets.view',
      permissionId: 'engine:secrets:view',
      resourceType: 'engine',
      operation: 'reveal',
      risk: 'high',
      audit: true,
      category: 'Engine Secrets',
      description: 'View engine authentication and credential-backed fields.',
      ui: [
        { surfaceId: 'engines.auth-fields', behavior: 'redact' },
        { surfaceId: 'engines.connection-secrets', behavior: 'redact' },
      ],
    },
  {
      actionId: 'engine.secrets.manage',
      permissionId: 'engine:secrets:manage',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'Engine Secrets',
      description: 'Create, replace, or clear engine authentication and credential-backed fields.',
      ui: [
        { surfaceId: 'engines.auth-fields.edit', behavior: 'disable' },
        { surfaceId: 'engines.connection-secrets.edit', behavior: 'disable' },
      ],
    },
  {
      actionId: 'engine.inventory.delete',
      permissionId: 'engine:delete',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'critical',
      audit: true,
      category: 'Engine Inventory',
      description: 'Delete an engine and prune related external registration and Engine Set materialization records.',
      ui: [{ surfaceId: 'engines.delete', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/engines-api/engines/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['legacy engine manage role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.saved-filters.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Engine Saved Filters',
      description: 'Read saved Mission Control filters for engines visible to the current user.',
      ui: [{ surfaceId: 'mission-control.saved-filters', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/engines-api/saved-filters',
          resourceResolver: 'engine.visibleCollection',
          additionalChecks: ['collection is filtered to engines returned by engineService.getUserEngines'],
        },
        {
          method: 'GET',
          route: '/engines-api/saved-filters/{id}',
          resourceResolver: 'engine.bySavedFilterId',
          additionalChecks: ['saved filter engine must be viewable by the current user'],
        },
      ],
    },
  {
      actionId: 'engine.saved-filters.manage',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'medium',
      audit: false,
      category: 'Engine Saved Filters',
      description: 'Create, update, or delete saved Mission Control filters for engines visible to the current user.',
      ui: [{ surfaceId: 'mission-control.saved-filters.manage', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/saved-filters',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId comes from request body and must be viewable by the current user'],
        },
        {
          method: 'PUT',
          route: '/engines-api/saved-filters/{id}',
          resourceResolver: 'engine.bySavedFilterId',
          additionalChecks: ['existing saved filter engine and optional replacement engineId must both be viewable by the current user'],
        },
        {
          method: 'DELETE',
          route: '/engines-api/saved-filters/{id}',
          resourceResolver: 'engine.bySavedFilterId',
          additionalChecks: ['saved filter engine must be viewable by the current user'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Batches',
      description: 'Read Mission Control async batch lists and batch detail.',
      ui: [{ surfaceId: 'mission-control.batches.list', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/batches',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/batches/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.process-instances.delete',
      permissionId: 'engine:instance:delete',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Create an async batch that deletes process instances on an engine.',
      ui: [{ surfaceId: 'mission-control.batches.delete-instances', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/batches/process-instances/delete',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.process-instances.suspend',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Create an async batch that suspends process instances on an engine.',
      ui: [{ surfaceId: 'mission-control.batches.suspend-instances', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/batches/process-instances/suspend',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.process-instances.activate',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Create an async batch that activates suspended process instances on an engine.',
      ui: [{ surfaceId: 'mission-control.batches.activate-instances', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/batches/process-instances/activate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.jobs.retry',
      permissionId: 'engine:instance:retry',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Create an async batch that retries failed jobs for process instances on an engine.',
      ui: [{ surfaceId: 'mission-control.batches.retry-jobs', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/batches/jobs/retries',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.suspension.update',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Suspend or resume an existing engine async batch.',
      ui: [{ surfaceId: 'mission-control.batches.suspension-toggle', behavior: 'disable' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/batches/{id}/suspended',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.cancel',
      permissionId: 'engine:process:cancel',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Cancel an engine async batch and mark the local batch record canceled.',
      ui: [{ surfaceId: 'mission-control.batches.cancel', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/mission-control-api/batches/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.batches.record.delete',
      permissionId: 'engine:instance:delete',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Mission Control Batches',
      description: 'Delete a completed, failed, or canceled local async batch record.',
      ui: [{ surfaceId: 'mission-control.batches.delete-record', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/mission-control-api/batches/{id}/record',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.decisions.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Decisions',
      description: 'Read deployed decision definitions and DMN XML from an engine.',
      ui: [{ surfaceId: 'mission-control.decisions.list', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/decision-definitions',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/decision-definitions/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/decision-definitions/{id}/xml',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.decisions.edit-target.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Decisions',
      description: 'Resolve a deployed decision definition back to a Starbase file edit target.',
      ui: [{ surfaceId: 'mission-control.decisions.edit-target', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/decision-definitions/edit-target',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'project:files:view on the resolved project is required before returning a target',
            'project:files:edit controls whether the returned target can be edited',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.decisions.evaluate',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'evaluate',
      risk: 'high',
      audit: true,
      category: 'Mission Control Decisions',
      description: 'Evaluate a deployed decision definition by id or key using the current compatibility permission.',
      ui: [{ surfaceId: 'mission-control.decisions.evaluate', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/decision-definitions/{id}/evaluate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
        {
          method: 'POST',
          route: '/mission-control-api/decision-definitions/key/{key}/evaluate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.migrations.preview',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'evaluate',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Migrations',
      description: 'Preview the number of process instances affected by a migration plan.',
      ui: [{ surfaceId: 'mission-control.migrations.preview', behavior: 'disable', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/migration/preview',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.migrations.plan.generate',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'evaluate',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Migrations',
      description: 'Generate an engine migration plan from source and target process definitions.',
      ui: [{ surfaceId: 'mission-control.migrations.plan.generate', behavior: 'disable', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/migration/generate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
        {
          method: 'POST',
          route: '/mission-control-api/migration/plan/generate',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from request body by action middleware',
            'documented compatibility path for the migration plan generation operation',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.migrations.plan.validate',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'evaluate',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Migrations',
      description: 'Validate an engine migration plan before execution.',
      ui: [{ surfaceId: 'mission-control.migrations.plan.validate', behavior: 'disable', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/migration/plan/validate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.migrations.active-sources.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Migrations',
      description: 'Read active source activity counts for process instances before migration.',
      ui: [{ surfaceId: 'mission-control.migrations.active-sources', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/migration/active-sources',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.migrations.execute-async',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Migrations',
      description: 'Execute a migration plan through an asynchronous engine batch.',
      ui: [{ surfaceId: 'mission-control.migrations.execute-async', behavior: 'disable', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/migration/execute-async',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.migrations.execute-direct',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Migrations',
      description: 'Execute a migration plan directly against selected process instances.',
      ui: [{ surfaceId: 'mission-control.migrations.execute-direct', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/migration/execute-direct',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read process instance lists and process instance details from an engine.',
      ui: [{ surfaceId: 'mission-control.process-instances.list', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'POST',
          route: '/mission-control-api/process-instances/preview-count',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.variables.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read runtime variables for a process instance using the current compatibility permission.',
      ui: [{ surfaceId: 'mission-control.process-instances.variables', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/variables',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.variable-history.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read variable history for a process instance variable using the current compatibility permission.',
      ui: [{ surfaceId: 'mission-control.process-instances.variable-history', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/variable-history',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.activity-tree.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read the runtime activity instance tree for a process instance.',
      ui: [{ surfaceId: 'mission-control.process-instances.activity-tree', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/activity-instances',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.activity-history.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read historic activity instances for a process instance.',
      ui: [{ surfaceId: 'mission-control.process-instances.activity-history', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/history/activity-instances',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.execution-details.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read lazy execution details for a process instance activity.',
      ui: [{ surfaceId: 'mission-control.process-instances.execution-details', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/execution-details',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.incidents.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control Process Instances',
      description: 'Read incidents for a process instance.',
      ui: [{ surfaceId: 'mission-control.process-instances.incidents', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/incidents',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.suspension.update',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Process Instances',
      description: 'Suspend or activate a process instance.',
      ui: [{ surfaceId: 'mission-control.process-instances.suspension', behavior: 'disable' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/process-instances/{id}/suspend',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
        {
          method: 'PUT',
          route: '/mission-control-api/process-instances/{id}/activate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.retry',
      permissionId: 'engine:instance:retry',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Process Instances',
      description: 'Retry failed jobs and external tasks for a process instance.',
      ui: [{ surfaceId: 'mission-control.process-instances.retry', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/process-instances/{id}/retry',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.modify',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Process Instances',
      description: 'Modify process instance execution directly on an engine.',
      ui: [{ surfaceId: 'mission-control.process-instances.modify', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/process-instances/{id}/modify',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.delete',
      permissionId: 'engine:instance:delete',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Mission Control Process Instances',
      description: 'Delete or cancel a process instance on an engine.',
      ui: [{ surfaceId: 'mission-control.process-instances.delete', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/mission-control-api/process-instances/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-instances.variables.update',
      permissionId: 'engine:variables:edit',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Process Instances',
      description: 'Create, update, or delete runtime variables on a process instance.',
      ui: [{ surfaceId: 'mission-control.process-instances.variables.update', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/process-instances/{id}/variables',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-definitions.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Process Definitions',
      description: 'Read process definitions, BPMN XML, and process definition runtime statistics from an engine.',
      ui: [{ surfaceId: 'mission-control.process-definitions.list', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/{id}/xml',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/resolve',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/{id}/active-activity-counts',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/{id}/activity-counts-by-state',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/key/{key}/statistics',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-definitions.edit-target.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Process Definitions',
      description: 'Resolve a deployed process definition back to a Starbase file edit target.',
      ui: [{ surfaceId: 'mission-control.process-definitions.edit-target', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/process-definitions/edit-target',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'project:files:view on the resolved project is required before returning a target',
            'project:files:edit controls whether the returned target can be edited',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-definitions.start',
      permissionId: 'engine:process:start',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Process Definitions',
      description: 'Start a new process instance from a deployed process definition key.',
      ui: [{ surfaceId: 'mission-control.process-definitions.start', behavior: 'disable', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/process-definitions/key/{key}/start',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-definitions.modification.execute-async',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Process Definitions',
      description: 'Create an asynchronous process definition modification batch.',
      ui: [{ surfaceId: 'mission-control.process-definitions.modification', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/process-definitions/{id}/modification/execute-async',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.process-definitions.restart.execute-async',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Process Definitions',
      description: 'Create an asynchronous process definition restart batch.',
      ui: [{ surfaceId: 'mission-control.process-definitions.restart', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/process-definitions/{id}/restart/execute-async',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.direct.process-instances.delete',
      permissionId: 'engine:instance:delete',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'critical',
      audit: true,
      category: 'Mission Control Direct Actions',
      description: 'Delete process instances directly without creating an engine batch.',
      ui: [{ surfaceId: 'mission-control.direct.process-instances.delete', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/direct/process-instances/delete',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.direct.process-instances.suspend',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Direct Actions',
      description: 'Suspend process instances directly without creating an engine batch.',
      ui: [{ surfaceId: 'mission-control.direct.process-instances.suspend', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/direct/process-instances/suspend',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.direct.process-instances.activate',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Direct Actions',
      description: 'Activate suspended process instances directly without creating an engine batch.',
      ui: [{ surfaceId: 'mission-control.direct.process-instances.activate', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/direct/process-instances/activate',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.direct.jobs.retry',
      permissionId: 'engine:instance:retry',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Direct Actions',
      description: 'Set retries for failed jobs directly without creating an engine batch.',
      ui: [{ surfaceId: 'mission-control.direct.jobs.retry', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/direct/jobs/retries',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.tasks.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Tasks',
      description: 'Read user tasks, task counts, task details, and task forms from an engine.',
      ui: [{ surfaceId: 'mission-control.tasks.list', behavior: 'hide', coverage: 'api-only' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/tasks',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/tasks/count',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/tasks/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/tasks/{id}/form',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.tasks.variables.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control Tasks',
      description: 'Read task variables using the current compatibility permission.',
      ui: [{ surfaceId: 'mission-control.tasks.variables', behavior: 'redact', coverage: 'api-only' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/tasks/{id}/variables',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.tasks.variables.update',
      permissionId: 'engine:variables:edit',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Tasks',
      description: 'Update task variables.',
      ui: [{ surfaceId: 'mission-control.tasks.variables.update', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/tasks/{id}/variables',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.tasks.assignment.update',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Tasks',
      description: 'Claim, unclaim, or set a task assignee.',
      ui: [{ surfaceId: 'mission-control.tasks.assignment', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/tasks/{id}/claim',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
        {
          method: 'POST',
          route: '/mission-control-api/tasks/{id}/unclaim',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
        {
          method: 'POST',
          route: '/mission-control-api/tasks/{id}/assignee',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.tasks.complete',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Tasks',
      description: 'Complete a user task.',
      ui: [{ surfaceId: 'mission-control.tasks.complete', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/tasks/{id}/complete',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control External Tasks',
      description: 'Read external tasks from an engine.',
      ui: [{ surfaceId: 'mission-control.external-tasks.list', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/external-tasks',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/failed-external-tasks',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.fetch-and-lock',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control External Tasks',
      description: 'Fetch and lock external tasks for worker execution.',
      ui: [{ surfaceId: 'mission-control.external-tasks.fetch-and-lock', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/external-tasks/fetchAndLock',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.complete',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control External Tasks',
      description: 'Complete an external task.',
      ui: [{ surfaceId: 'mission-control.external-tasks.complete', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/external-tasks/{id}/complete',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.failure',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control External Tasks',
      description: 'Report external task failure and retry metadata.',
      ui: [{ surfaceId: 'mission-control.external-tasks.failure', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/external-tasks/{id}/failure',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.bpmn-error',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control External Tasks',
      description: 'Report an external task BPMN business error.',
      ui: [{ surfaceId: 'mission-control.external-tasks.bpmn-error', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/external-tasks/{id}/bpmnError',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.extend-lock',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control External Tasks',
      description: 'Extend an external task lock.',
      ui: [{ surfaceId: 'mission-control.external-tasks.extend-lock', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/external-tasks/{id}/extendLock',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.external-tasks.unlock',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control External Tasks',
      description: 'Unlock an external task.',
      ui: [{ surfaceId: 'mission-control.external-tasks.unlock', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/external-tasks/{id}/unlock',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.messages.correlate',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Messages',
      description: 'Correlate a message into process execution on an engine.',
      ui: [{ surfaceId: 'mission-control.messages.correlate', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/messages',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.signals.deliver',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Signals',
      description: 'Deliver a signal event into process execution on an engine.',
      ui: [{ surfaceId: 'mission-control.signals.deliver', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/signals',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.tasks.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control History',
      description: 'Read historic task instances from an engine.',
      ui: [{ surfaceId: 'mission-control.history.tasks', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/tasks',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.variables.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control History',
      description: 'Read historic variable instances from an engine using the current compatibility permission.',
      ui: [{ surfaceId: 'mission-control.history.variables', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/variables',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
        {
          method: 'GET',
          route: '/mission-control-api/history/variable-instances',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.decisions.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control History',
      description: 'Read historic decision instances from an engine using the current compatibility permission.',
      ui: [{ surfaceId: 'mission-control.history.decisions', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/decisions',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.decisions.inputs.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control History',
      description: 'Read input payloads for a historic decision instance.',
      ui: [{ surfaceId: 'mission-control.history.decisions.inputs', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/decisions/{id}/inputs',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.decisions.outputs.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control History',
      description: 'Read output payloads for a historic decision instance.',
      ui: [{ surfaceId: 'mission-control.history.decisions.outputs', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/decisions/{id}/outputs',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.user-operations.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control History',
      description: 'Read user operation history from an engine.',
      ui: [{ surfaceId: 'mission-control.history.user-operations', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/user-operations',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.history.process-instances.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'high',
      audit: false,
      category: 'Mission Control History',
      description: 'Read historic process instance lists and details from an engine.',
      ui: [{ surfaceId: 'mission-control.history.process-instances', behavior: 'redact', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/history/process-instances',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
        {
          method: 'GET',
          route: '/mission-control-api/history/process-instances/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: [
            'engineId is resolved from query string by action middleware',
            'response payload is passed through the PII redaction service',
          ],
        },
      ],
    },
  {
      actionId: 'engine.runtime.jobs.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Jobs',
      description: 'Read executable jobs from an engine.',
      ui: [{ surfaceId: 'mission-control.jobs.list', behavior: 'hide', coverage: 'runtime-enforced' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/jobs',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/jobs/{id}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/process-instances/{id}/jobs',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.jobs.execute',
      permissionId: 'engine:instance:retry',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control Jobs',
      description: 'Execute a job immediately.',
      ui: [{ surfaceId: 'mission-control.jobs.execute', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'POST',
          route: '/mission-control-api/jobs/{id}/execute',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.jobs.retries.update',
      permissionId: 'engine:instance:retry',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Jobs',
      description: 'Set retry count for a job.',
      ui: [{ surfaceId: 'mission-control.jobs.retries', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/jobs/{id}/retries',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.jobs.suspension.update',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Jobs',
      description: 'Suspend or activate a job.',
      ui: [{ surfaceId: 'mission-control.jobs.suspension', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/jobs/{id}/suspended',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.job-definitions.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Jobs',
      description: 'Read job definitions from an engine.',
      ui: [{ surfaceId: 'mission-control.job-definitions.list', behavior: 'hide', coverage: 'api-only' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/job-definitions',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.job-definitions.retries.update',
      permissionId: 'engine:instance:retry',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Jobs',
      description: 'Set retry count for a job definition.',
      ui: [{ surfaceId: 'mission-control.job-definitions.retries', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/job-definitions/{id}/retries',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.job-definitions.suspension.update',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control Jobs',
      description: 'Suspend or activate a job definition.',
      ui: [{ surfaceId: 'mission-control.job-definitions.suspension', behavior: 'disable', coverage: 'api-only' }],
      routes: [
        {
          method: 'PUT',
          route: '/mission-control-api/job-definitions/{id}/suspended',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from request body by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.runtime.metrics.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Mission Control Metrics',
      description: 'Read engine runtime metrics.',
      ui: [{ surfaceId: 'mission-control.metrics', behavior: 'hide', coverage: 'api-only' }],
      routes: [
        {
          method: 'GET',
          route: '/mission-control-api/metrics',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
        {
          method: 'GET',
          route: '/mission-control-api/metrics/{name}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engineId is resolved from query string by action middleware'],
        },
      ],
    },
  {
      actionId: 'engine.members.read',
      permissionId: 'engine:members:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Engine Members',
      description: 'Read engine members, pending engine invitations, and the current user engine role.',
      ui: [
        { surfaceId: 'engine.members.list', behavior: 'hide' },
        { surfaceId: 'engine.detail.access', behavior: 'hide' },
      ],
      routes: [
        {
          method: 'GET',
          route: '/engines-api/engines/{engineId}/members',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:members:manage, engine:members:lookup, engine:instance:view, or legacy engine view role also accepted for compatibility'],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{engineId}/my-role',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:members:manage, engine:members:lookup, engine:instance:view, or legacy engine view role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.members.lookup',
      permissionId: 'engine:members:lookup',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Engine Members',
      description: 'Look up candidate users for engine membership changes.',
      ui: [{ surfaceId: 'engine.members.lookup', behavior: 'disable' }],
      routes: [{ method: 'GET', route: '/engines-api/engines/{engineId}/members/lookup', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'engine.members.invite',
      permissionId: 'engine:members:invite',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Members',
      description: 'Invite users to an engine and manage pending manual engine invitations.',
      ui: [{ surfaceId: 'engine.members.invite', behavior: 'disable' }],
      routes: [
        { method: 'GET', route: '/engines-api/engines/{engineId}/members/capabilities', resourceResolver: 'engine.byId' },
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/members',
          resourceResolver: 'engine.byId',
          additionalChecks: ['Used when the target email does not resolve to an existing local-login user'],
        },
        { method: 'POST', route: '/engines-api/engines/{engineId}/pending-invites/{invitationId}/reissue', resourceResolver: 'engine.byId' },
      ],
    },
  {
      actionId: 'engine.members.add',
      permissionId: 'engine:members:add',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Members',
      description: 'Add an existing user to an engine.',
      ui: [{ surfaceId: 'engine.members.add', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/members',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine.members.invite when the target email must be invited instead of directly added'],
        },
      ],
    },
  {
      actionId: 'engine.members.update-role',
      permissionId: 'engine:members:update-role',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Members',
      description: 'Update an operator or deployer role on an engine.',
      ui: [{ surfaceId: 'engine.members.update-role', behavior: 'disable' }],
      routes: [{ method: 'PATCH', route: '/engines-api/engines/{engineId}/members/{userId}', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'engine.members.remove',
      permissionId: 'engine:members:remove',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Members',
      description: 'Remove an operator or deployer from an engine.',
      ui: [{ surfaceId: 'engine.members.remove', behavior: 'disable' }],
      routes: [{ method: 'DELETE', route: '/engines-api/engines/{engineId}/members/{userId}', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'engine.delegate.manage',
      permissionId: 'engine:delegate:manage',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Governance',
      description: 'Assign or remove an engine delegate.',
      ui: [{ surfaceId: 'engine.delegate.manage', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/engines-api/engines/{engineId}/delegate', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'engine.ownership.transfer',
      permissionId: 'engine:ownership:transfer',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'Engine Governance',
      description: 'Transfer engine ownership.',
      ui: [{ surfaceId: 'engine.ownership.transfer', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/engines-api/engines/{engineId}/transfer-ownership', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'engine.environment.set',
      permissionId: 'engine:environment:set',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Environment',
      description: 'Set an engine environment tag.',
      ui: [{ surfaceId: 'engine.environment.tag', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/environment',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:edit or legacy engine manage role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.environment.lock',
      permissionId: 'engine:environment:lock',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Environment',
      description: 'Lock or unlock an engine environment.',
      ui: [{ surfaceId: 'engine.environment.lock', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/lock',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:edit or legacy engine manage role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.project-access.requests.read',
      permissionId: 'engine:project-access:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Engine Targets',
      description: 'Read project access requests and deployment targets for an engine.',
      ui: [
        { surfaceId: 'engine.project-access.requests', behavior: 'hide' },
        { surfaceId: 'engine.detail.deployment-targets', behavior: 'hide' },
      ],
      routes: [
        {
          method: 'GET',
          route: '/engines-api/engines/{engineId}/access-requests',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:members:manage or legacy engine manage role also accepted for compatibility'],
        },
        {
          method: 'GET',
          route: '/engines-api/engines/{id}/project-targets',
          resourceResolver: 'engine.byId',
          additionalChecks: ['returns configured project-engine deployment targets for this engine'],
        },
      ],
    },
  {
      actionId: 'engine.project-access.requests.approve',
      permissionId: 'engine:project-access:approve',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Approve a project access request for an engine.',
      ui: [{ surfaceId: 'engine.project-access.approve', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/access-requests/{requestId}/approve',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:members:manage or legacy engine manage role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.project-access.requests.deny',
      permissionId: 'engine:project-access:deny',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Deny a project access request for an engine.',
      ui: [{ surfaceId: 'engine.project-access.deny', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/access-requests/{requestId}/deny',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:members:manage or legacy engine manage role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.project-access.revoke',
      permissionId: 'engine:project-access:revoke',
      resourceType: 'engine',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Revoke a project target from an engine.',
      ui: [{ surfaceId: 'engine.project-access.revoke', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/engines-api/engines/{engineId}/projects/{projectId}',
          resourceResolver: 'engine.byId',
          additionalChecks: ['engine:members:manage or legacy engine manage role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'engine.variables.update',
      permissionId: 'engine:variables:edit',
      resourceType: 'engine',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Mission Control',
      description: 'Create, update, or delete runtime variables.',
      // Aggregate reporting action; concrete runtime controls own the mounted UI surfaces.
      ui: [{ surfaceId: 'mission-control.variables.actions', behavior: 'disable', coverage: 'api-only' }],
    },
  {
      actionId: 'engine.instances.read',
      permissionId: 'engine:instance:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Mission Control',
      description: 'Read process and decision runtime instances.',
      ui: [{ surfaceId: 'mission-control.instances', behavior: 'hide' }],
    },
  {
      actionId: 'engine.instances.mutate',
      permissionId: 'engine:process:modify',
      resourceType: 'engine',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Mission Control',
      description: 'Modify, migrate, retry, cancel, or batch mutate runtime instances.',
      // This aggregate action is retained for audit/reporting. Concrete runtime
      // operation actions own the mounted controls and their frontend guards.
      ui: [{ surfaceId: 'mission-control.instances.actions', behavior: 'disable', coverage: 'api-only' }],
    },
] satisfies AuthzActionDefinition[];
