import type { AuthzActionDefinition } from '../permission-actions.js';

export const PLATFORM_AUTHZ_ACTIONS = [
  {
      actionId: 'platform.authz.permissions.read',
      permissionId: 'platform:authz:roles:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Access Control',
      description: 'Read the permission catalog.',
      ui: [{ surfaceId: 'admin.access-control.permissions', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/permissions', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.authz.roles.read',
      permissionId: 'platform:authz:roles:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Access Control',
      description: 'Read role definitions and role permission counts.',
      ui: [{ surfaceId: 'admin.access-control.roles', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/roles', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/roles/{id}', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.authz.roles.manage',
      permissionId: 'platform:authz:roles:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Access Control',
      description: 'Create or update custom roles and role permissions.',
      ui: [{ surfaceId: 'admin.access-control.roles.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/permissions', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/roles', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/authz/roles/{id}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/authz/roles/{id}', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.config-bundles.view',
      permissionId: 'platform:config-bundles:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Configuration Bundles',
      description: 'View configuration bundle apply history and replay task receipts.',
      ui: [{ surfaceId: 'admin.configuration-bundles.history', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/config-bundles/runs', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/config-bundles/runs/{id}', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/config-bundles/runs/{id}/identity-replay-tasks', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/config-bundles/runs/{id}/runtime-reconciliation-tasks', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.config-bundles.preview',
      permissionId: 'platform:config-bundles:preview',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Configuration Bundles',
      description: 'Import, preview, diff, and validate configuration bundles.',
      ui: [{ surfaceId: 'admin.configuration-bundles.preview', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/config-bundles/preview', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/config-bundles/validate-secret-refs', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/config-bundles/import-zip', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/config-bundles/import-url', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/config-bundles/diff', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.config-bundles.apply',
      permissionId: 'platform:config-bundles:apply',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Configuration Bundles',
      description: 'Apply an exact reviewed configuration bundle preview.',
      ui: [{ surfaceId: 'admin.configuration-bundles.apply', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/config-bundles/apply', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.config-bundles.export',
      permissionId: 'platform:config-bundles:export',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Configuration Bundles',
      description: 'Export configuration-managed bundle state.',
      ui: [{ surfaceId: 'admin.configuration-bundles.export', behavior: 'disable' }],
      routes: [
        { method: 'GET', route: '/api/authz/config-bundles/export', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.authz.assignments.read',
      permissionId: 'platform:authz:roles:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Access Control',
      description: 'Read role assignments for users, groups, API clients, and service accounts.',
      ui: [{ surfaceId: 'admin.access-control.assignments', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/role-assignments', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.authz.assignments.create',
      permissionId: 'platform:authz:roles:manage',
      resourceType: 'platform',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Access Control',
      description: 'Create a scoped role assignment.',
      ui: [{ surfaceId: 'admin.access-control.assignments.create', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/api/authz/role-assignments', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.authz.assignments.delete',
      permissionId: 'platform:authz:roles:manage',
      resourceType: 'platform',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Access Control',
      description: 'Remove a scoped role assignment.',
      ui: [{ surfaceId: 'admin.access-control.assignments.delete', behavior: 'disable' }],
      routes: [{ method: 'DELETE', route: '/api/authz/role-assignments/:id', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.authz.groups.read',
      permissionId: 'platform:authz:roles:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Access Control',
      description: 'Read internal authorization groups and memberships.',
      ui: [{ surfaceId: 'admin.access-control.groups', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/groups', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/group-memberships', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.authz.groups.manage',
      permissionId: 'platform:authz:roles:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Access Control',
      description: 'Create, update, archive, and manage memberships for internal authorization groups.',
      ui: [{ surfaceId: 'admin.access-control.groups.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/groups', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/authz/groups/:id', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/authz/groups/:id', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/group-memberships', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/authz/group-memberships/:id', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.authz.policies.read',
      permissionId: 'platform:authz:roles:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Access Control',
      description: 'Read authorization policies.',
      ui: [{ surfaceId: 'admin.access-control.policies', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/policies', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.authz.policies.manage',
      permissionId: 'platform:authz:roles:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Access Control',
      description: 'Create, update, or delete authorization policies.',
      ui: [{ surfaceId: 'admin.access-control.policies.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/policies', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/authz/policies/{id}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/authz/policies/{id}', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.authz.evaluate',
      permissionId: 'platform:authz:check',
      resourceType: 'platform',
      operation: 'evaluate',
      risk: 'medium',
      audit: true,
      category: 'Access Control',
      description: 'Evaluate and explain access for a principal/action/resource tuple.',
      ui: [{ surfaceId: 'admin.access-control.effective-access', behavior: 'hide' }],
      routes: [{ method: 'POST', route: '/api/authz/evaluate', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.sso.engine-assignments.read',
      permissionId: 'platform:sso-assignments:view',
      resourceType: 'sso_mapping',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'SSO',
      description: 'Read SSO engine assignment mappings.',
      ui: [{ surfaceId: 'admin.access-control.sso-engine-assignments', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/sso-assignment-mappings', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/sso-engine-access-snapshots', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/sso-engine-access-snapshots/:engineId', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/sso-sync-runs', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/sso-sync-runs/:id/events', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.sso.engine-assignments.manage',
      permissionId: 'platform:sso-assignments:manage',
      resourceType: 'sso_mapping',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'SSO',
      description: 'Create, update, disable, delete, or test SSO engine assignment mappings.',
      ui: [{ surfaceId: 'admin.access-control.sso-engine-assignments.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/sso-assignment-mappings', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/sso-assignment-mappings/{id}/migrate-provider-neutral', resourceResolver: 'ssoMapping.byId' },
        { method: 'PUT', route: '/api/authz/sso-assignment-mappings/:id', resourceResolver: 'ssoMapping.byId' },
        { method: 'DELETE', route: '/api/authz/sso-assignment-mappings/:id', resourceResolver: 'ssoMapping.byId' },
        { method: 'POST', route: '/api/authz/sso-assignment-mappings/test', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/sso-sync-runs/reconcile', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/engines/:engineId/access/transition-cleanup-preview', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/engines/:engineId/access/transition-cleanup', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.sso.group-mappings.read',
      permissionId: 'platform:sso-assignments:view',
      resourceType: 'sso_mapping',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'SSO',
      description: 'Read SSO claim-to-group mappings.',
      ui: [{ surfaceId: 'admin.access-control.sso-group-mappings', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/sso-group-mappings', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/identity/mappings', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/legacy-mapping-coverage', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/legacy-mapping-retirement-readiness', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.sso.group-mappings.manage',
      permissionId: 'platform:sso-assignments:manage',
      resourceType: 'sso_mapping',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'SSO',
      description: 'Create, update, disable, delete, or test SSO claim-to-group mappings.',
      ui: [{ surfaceId: 'admin.access-control.sso-group-mappings.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/sso-group-mappings', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/sso-group-mappings/{id}/migrate-provider-neutral', resourceResolver: 'ssoMapping.byId' },
        { method: 'PUT', route: '/api/authz/sso-group-mappings/:id', resourceResolver: 'ssoMapping.byId' },
        { method: 'DELETE', route: '/api/authz/sso-group-mappings/:id', resourceResolver: 'ssoMapping.byId' },
        { method: 'POST', route: '/api/authz/sso-group-mappings/test', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/mappings', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/mappings/provision-access', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/identity/mappings/{id}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/identity/mappings/{id}', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/mappings/test', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/mappings/stored-snapshot-preview', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/legacy-mapping-coverage/{id}/verify', resourceResolver: 'ssoMapping.byId' },
        { method: 'POST', route: '/api/authz/legacy-mapping-retirement/disable', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/legacy-mapping-retirement/disable-global', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.sso.platform-role-mappings.read',
      permissionId: 'platform:sso-platform-role-mappings:view',
      resourceType: 'sso_mapping',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'SSO',
      description: 'Read legacy SSO claim mappings that provision platform roles.',
      ui: [{ surfaceId: 'admin.sso.role-mappings', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/sso-mappings', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.sso.platform-role-mappings.manage',
      permissionId: 'platform:sso-platform-role-mappings:manage',
      resourceType: 'sso_mapping',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'SSO',
      description: 'Create, update, delete, or test legacy SSO claim mappings that provision platform roles.',
      ui: [{ surfaceId: 'admin.sso.role-mappings.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/sso-mappings', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/sso-mappings/{id}/migrate-provider-neutral', resourceResolver: 'ssoMapping.byId' },
        { method: 'PUT', route: '/api/authz/sso-mappings/{id}', resourceResolver: 'ssoMapping.byId' },
        { method: 'DELETE', route: '/api/authz/sso-mappings/{id}', resourceResolver: 'ssoMapping.byId' },
        { method: 'POST', route: '/api/authz/sso-mappings/test', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/legacy-mapping-retirement/disable-global', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.engine-sets.read',
      permissionId: 'platform:engine-sets:view',
      resourceType: 'engine_set',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Engine Sets',
      description: 'Read Engine Sets and materialized engine matches.',
      ui: [{ surfaceId: 'admin.access-control.engine-sets', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/engine-sets', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/engine-sets/:id', resourceResolver: 'engineSet.byId' },
        { method: 'GET', route: '/api/authz/runtime-resources', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/runtime-resource-sets', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.engine-sets.manage',
      permissionId: 'platform:engine-sets:manage',
      resourceType: 'engine_set',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Engine Sets',
      description: 'Create, update, archive, preview, and refresh Engine Set materializations.',
      ui: [{ surfaceId: 'admin.access-control.engine-sets.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/engine-sets', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/authz/engine-sets/:id', resourceResolver: 'engineSet.byId' },
        { method: 'DELETE', route: '/api/authz/engine-sets/:id', resourceResolver: 'engineSet.byId' },
        { method: 'POST', route: '/api/authz/engine-sets/preview', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/engine-sets/:id/materialize', resourceResolver: 'engineSet.byId' },
        { method: 'POST', route: '/api/authz/runtime-resource-sets/:id/materialize', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/runtime-resources/:id/reconcile', resourceResolver: 'engine.byId' },
      ],
    },
  {
      actionId: 'platform.project-engine-targets.read',
      permissionId: 'platform:project-engine-targets:view',
      resourceType: 'project_engine_target',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Read project-to-engine targets and mode flags.',
      ui: [{ surfaceId: 'admin.access-control.project-engine-targets', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/authz/project-engine-targets', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/project-engine-targets/:id', resourceResolver: 'projectEngineTarget.byId' },
      ],
    },
  {
      actionId: 'platform.project-engine-targets.manage',
      permissionId: 'platform:project-engine-targets:manage',
      resourceType: 'project_engine_target',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Create, update, archive, or reconcile project-to-engine targets.',
      ui: [{ surfaceId: 'admin.access-control.project-engine-targets.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/project-engine-targets', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/authz/project-engine-targets/:id', resourceResolver: 'projectEngineTarget.byId' },
        { method: 'DELETE', route: '/api/authz/project-engine-targets/:id', resourceResolver: 'projectEngineTarget.byId' },
        { method: 'POST', route: '/api/authz/project-engine-targets/sync-legacy', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.dashboard.read',
      permissionId: 'platform:dashboard:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Dashboard',
      description: 'Read current-user dashboard context and own-resource summary statistics.',
      ui: [{ surfaceId: 'dashboard.route', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/dashboard/context', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/dashboard/stats', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.users.read',
      permissionId: 'platform:users:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Users',
      description: 'Read platform users.',
      ui: [{ surfaceId: 'admin.users', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/api/users',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:user:view and platform:user:manage are accepted for compatibility'],
        },
        {
          method: 'GET',
          route: '/api/users/{id}',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:user:view and platform:user:manage are accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'platform.users.create',
      permissionId: 'platform:users:create',
      resourceType: 'platform',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Users',
      description: 'Create a pending platform user and onboarding invitation.',
      ui: [{ surfaceId: 'admin.users.create', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/api/users',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:user:manage is accepted for compatibility; manual delivery may return reveal-once onboarding details'],
        },
      ],
    },
  {
      actionId: 'platform.users.update',
      permissionId: 'platform:users:update',
      resourceType: 'platform',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Users',
      description: 'Update platform user profile, platform role, or active state.',
      ui: [{ surfaceId: 'admin.users.edit', behavior: 'disable' }],
      routes: [
        {
          method: 'PUT',
          route: '/api/users/{id}',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:user:manage is accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'platform.users.deactivate',
      permissionId: 'platform:users:deactivate',
      resourceType: 'platform',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Users',
      description: 'Deactivate a platform user without permanently deleting the account.',
      ui: [{ surfaceId: 'admin.users.deactivate', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/api/users/{id}',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:users:delete and platform:user:manage are accepted for compatibility; caller cannot deactivate self'],
        },
      ],
    },
  {
      actionId: 'platform.users.permanent-delete',
      permissionId: 'platform:users:permanent-delete',
      resourceType: 'platform',
      operation: 'delete',
      risk: 'critical',
      audit: true,
      category: 'Users',
      description: 'Permanently delete a safe pending or inactive local platform user.',
      ui: [{ surfaceId: 'admin.users.permanent-delete', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/api/users/{id}/permanent',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:user:manage is accepted for compatibility; local login must be enabled; caller cannot delete self'],
        },
      ],
    },
  {
      actionId: 'platform.users.unlock',
      permissionId: 'platform:users:unlock',
      resourceType: 'platform',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Users',
      description: 'Unlock a locked platform user account.',
      ui: [{ surfaceId: 'admin.users.unlock', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/api/users/{id}/unlock',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform:user:manage is accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'platform.users.manage',
      permissionId: 'platform:users:update',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Users',
      description: 'Create, update, deactivate, delete, or unlock users.',
      ui: [{ surfaceId: 'admin.users.actions', behavior: 'disable' }],
    },
  {
      actionId: 'invitations.create',
      permissionId: 'platform:users:create',
      resourceType: 'platform',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Invitations',
      description: 'Create tenant, project, or engine invitations after the target resource permission branch passes.',
      ui: [{ surfaceId: 'invitations.create', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/api/t/:tenantSlug/invitations',
          resourceResolver: 'platform.self',
          additionalChecks: [
            'tenant invite requires platform:users:create or platform:user:manage',
            'project invite requires project:members:manage on body.resourceId',
            'engine invite requires engine:members:manage on body.resourceId',
            'manual delivery may return reveal-once onboarding details',
          ],
        },
      ],
    },
  {
      actionId: 'platform.settings.read',
      permissionId: 'platform:settings:manage',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Settings',
      description: 'Read platform setup, branding, environment tag, and email settings.',
      ui: [{ surfaceId: 'admin.settings', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/admin/setup-status', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/settings', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/branding', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/environments', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/email-configs', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/email-configs/{id}', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/email-platform-name', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/email-templates', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/email-templates/{id}', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/email-templates/{id}/preview', resourceResolver: 'platform.self' },
        {
          method: 'GET',
          route: '/',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: [
            'scanner-local alias for mounted /api/admin/settings, /api/admin/branding, and /api/admin/environments subrouters',
          ],
        },
      ],
    },
  {
      actionId: 'platform.settings.manage',
      permissionId: 'platform:settings:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Settings',
      description: 'Manage platform setup, branding, environment tag, and email settings.',
      ui: [{ surfaceId: 'admin.settings.actions', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/admin/mark-setup-complete', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/admin/settings', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/admin/branding', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/admin/branding', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/environments', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/admin/environments/{id}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/admin/environments/{id}', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/environments/reorder', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/email-configs', resourceResolver: 'platform.self' },
        { method: 'PATCH', route: '/api/admin/email-configs/{id}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/admin/email-configs/{id}', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/email-configs/{id}/set-default', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/email-configs/{id}/test', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/admin/email-platform-name', resourceResolver: 'platform.self' },
        { method: 'PATCH', route: '/api/admin/email-templates/{id}', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/email-templates/{id}/reset', resourceResolver: 'platform.self' },
        {
          method: 'PUT',
          route: '/',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: [
            'scanner-local alias for mounted /api/admin/settings and /api/admin/branding subrouters',
          ],
        },
        {
          method: 'DELETE',
          route: '/',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/branding reset route'],
        },
        {
          method: 'POST',
          route: '/',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/environments create route'],
        },
        {
          method: 'PUT',
          route: '/{id}',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/environments/{id} update route'],
        },
        {
          method: 'DELETE',
          route: '/{id}',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/environments/{id} delete route'],
        },
        {
          method: 'POST',
          route: '/reorder',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/environments/reorder route'],
        },
      ],
    },
  {
      actionId: 'platform.governance.read',
      permissionId: 'platform:settings:manage',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Governance',
      description: 'Read platform governance user, project, and engine assignment candidates.',
      ui: [{ surfaceId: 'admin.governance', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/admin/users/search', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/projects', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/admin/engines', resourceResolver: 'platform.self' },
        {
          method: 'GET',
          route: '/users/search',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/users/search route'],
        },
        {
          method: 'GET',
          route: '/projects',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/projects route'],
        },
        {
          method: 'GET',
          route: '/engines',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/engines route'],
        },
      ],
    },
  {
      actionId: 'platform.governance.manage',
      permissionId: 'platform:settings:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Governance',
      description: 'Assign platform-governed project and engine owners or delegates.',
      ui: [{ surfaceId: 'admin.governance.actions', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/admin/projects/{projectId}/assign-owner', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/projects/{projectId}/assign-delegate', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/engines/{engineId}/assign-owner', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/admin/engines/{engineId}/assign-delegate', resourceResolver: 'platform.self' },
        {
          method: 'POST',
          route: '/projects/{projectId}/assign-owner',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/projects/{projectId}/assign-owner route'],
        },
        {
          method: 'POST',
          route: '/projects/{projectId}/assign-delegate',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/projects/{projectId}/assign-delegate route'],
        },
        {
          method: 'POST',
          route: '/engines/{engineId}/assign-owner',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/engines/{engineId}/assign-owner route'],
        },
        {
          method: 'POST',
          route: '/engines/{engineId}/assign-delegate',
          resourceResolver: 'platform.self',
          openApi: false,
          additionalChecks: ['scanner-local alias for mounted /api/admin/engines/{engineId}/assign-delegate route'],
        },
      ],
    },
  {
      actionId: 'platform.sso.providers.read',
      permissionId: 'platform:sso-providers:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'SSO',
      description: 'Read configured SSO identity providers.',
      ui: [{ surfaceId: 'admin.sso.providers', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/api/identity/providers', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/identity/providers/{key}', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/identity/providers/{key}/sync-runs', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/identity/providers/{key}/sync-runs/{runId}/events', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.sso.providers.manage',
      permissionId: 'platform:sso-providers:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'SSO',
      description: 'Create, update, delete, enable, or disable SSO identity providers.',
      ui: [{ surfaceId: 'admin.sso.providers.actions', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/identity/providers', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/providers/{key}/external-identities/unlink', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/identity/providers/{key}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/identity/providers/{key}', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/providers/{key}/reconcile', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/providers/{key}/reconciliation-preview', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/providers/{key}/replay-memberships', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/identity/providers/{key}/test-connection', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.api-clients.read',
      permissionId: 'platform:api-clients:view',
      resourceType: 'api_client',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'API Clients',
      description: 'List API client machine identities.',
      ui: [{ surfaceId: 'admin.access-control.api-clients', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/api-clients', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.api-clients.manage',
      permissionId: 'platform:api-clients:manage',
      resourceType: 'api_client',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'API Clients',
      description: 'Create, revoke, or reveal API client credentials.',
      ui: [{ surfaceId: 'admin.access-control.api-clients', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/api-clients', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/api-clients/{id}/rotate', resourceResolver: 'apiClient.byId' },
        { method: 'DELETE', route: '/api/authz/api-clients/{id}', resourceResolver: 'apiClient.byId' },
      ],
    },
  {
      actionId: 'platform.service-accounts.read',
      permissionId: 'platform:service-accounts:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'Service Accounts',
      description: 'List service-account machine identities.',
      ui: [{ surfaceId: 'admin.access-control.service-accounts', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/service-accounts', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.service-accounts.manage',
      permissionId: 'platform:service-accounts:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'Service Accounts',
      description: 'Create, revoke, or reveal service-account credentials.',
      ui: [{ surfaceId: 'admin.access-control.service-accounts', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/service-accounts', resourceResolver: 'platform.self' },
        { method: 'POST', route: '/api/authz/service-accounts/{id}/rotate', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/authz/service-accounts/{id}', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.external-engine-systems.read',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'External Engine Registration',
      description: 'Read external engine source systems and their default ownership policy.',
      ui: [{ surfaceId: 'admin.access-control.external-engine-systems', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/external-engine-systems', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.external-engine-systems.manage',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'External Engine Registration',
      description: 'Create, update, or archive external engine source systems.',
      ui: [{ surfaceId: 'admin.access-control.external-engine-systems.actions', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/external-engine-systems', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/api/authz/external-engine-systems/{id}', resourceResolver: 'platform.self' },
        { method: 'DELETE', route: '/api/authz/external-engine-systems/{id}', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.external-engines.read',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'External Engine Registration',
      description: 'Read externally registered engine inventory.',
      ui: [{ surfaceId: 'admin.access-control.external-engines', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/external-engines', resourceResolver: 'platform.self' }],
    },
  {
      actionId: 'platform.external-engines.audit.read',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: true,
      category: 'External Engine Registration',
      description: 'Read audit events for an externally registered engine.',
      ui: [{ surfaceId: 'admin.access-control.external-engines.audit', behavior: 'hide' }],
      routes: [{ method: 'GET', route: '/api/authz/external-engines/{id}/audit', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'platform.external-engines.reconcile',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'engine',
      operation: 'sync',
      risk: 'high',
      audit: true,
      category: 'External Engine Registration',
      description: 'Reconcile externally registered engine capability status and Engine Set materializations.',
      ui: [{ surfaceId: 'admin.access-control.external-engines.reconcile', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/api/authz/external-engines/{id}/reconcile', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'platform.external-engines.lifecycle.manage',
      permissionId: 'platform:engine-registration:manage',
      resourceType: 'engine',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'External Engine Registration',
      description: 'Decommission or reactivate externally registered engines from the platform-admin inventory.',
      ui: [{ surfaceId: 'admin.access-control.external-engines.lifecycle-actions', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/external-engines/{id}/decommission', resourceResolver: 'engine.byId' },
        { method: 'POST', route: '/api/authz/external-engines/{id}/reactivate', resourceResolver: 'engine.byId' },
      ],
    },
  {
      actionId: 'platform.git.providers.manage',
      permissionId: 'platform:git-provider:manage',
      resourceType: 'platform',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Git',
      description: 'Read and update platform Git provider administration settings, including secret-backed OAuth configuration.',
      ui: [{ surfaceId: 'admin.git-providers', behavior: 'disable' }],
      routes: [
        { method: 'GET', route: '/git-api/admin/providers', resourceResolver: 'platform.self' },
        { method: 'PUT', route: '/git-api/admin/providers/:id', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.audit.read',
      permissionId: 'platform:audit:view',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Audit',
      description: 'Read audit events.',
      ui: [{ surfaceId: 'admin.audit', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/api/audit/logs',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform.audit.unredacted.read when unredacted audit payloads are requested'],
        },
        {
          method: 'GET',
          route: '/api/audit/logs/user/{userId}',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform.audit.unredacted.read when unredacted audit payloads are requested'],
        },
        {
          method: 'GET',
          route: '/api/audit/logs/resource/{resourceType}/{resourceId}',
          resourceResolver: 'platform.self',
          additionalChecks: ['platform.audit.unredacted.read when unredacted audit payloads are requested'],
        },
        { method: 'GET', route: '/api/audit/stats', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/audit/actions', resourceResolver: 'platform.self' },
        { method: 'GET', route: '/api/authz/audit', resourceResolver: 'platform.self' },
      ],
    },
  {
      actionId: 'platform.audit.unredacted.read',
      permissionId: 'platform:audit:unredacted-view',
      resourceType: 'platform',
      operation: 'reveal',
      risk: 'critical',
      audit: true,
      category: 'Audit',
      description: 'Read audit fields that normally require redaction.',
      ui: [{ surfaceId: 'admin.audit.unredacted-fields', behavior: 'redact' }],
    },
] satisfies AuthzActionDefinition[];
