import type { AuthzActionDefinition } from '../permission-actions.js';

export const PROJECT_AUTHZ_ACTIONS = [
  {
      actionId: 'project.deployment-eligibility.evaluate',
      permissionId: 'platform:project-engine-targets:view',
      resourceType: 'project_engine_target',
      operation: 'evaluate',
      risk: 'medium',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Evaluate whether a user can deploy from a project to an engine.',
      ui: [{ surfaceId: 'project.deploy.eligibility', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/api/authz/project-engine-targets/evaluate', resourceResolver: 'projectEngineTarget.byProjectAndEngine' },
      ],
    },
  {
      actionId: 'starbase.bridge.mission-control.evaluate',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'evaluate',
      risk: 'medium',
      audit: false,
      category: 'Starbase Bridge',
      description: 'Evaluate whether a Starbase project file can open the matching Mission Control runtime view.',
      ui: [{ surfaceId: 'starbase.bridge.mission-control', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/api/starbase/bridge/mission-control/evaluate',
          resourceResolver: 'project.byId',
          additionalChecks: [
            'engine:instance:view is required on the matching runtime engine',
            'an active project-engine target must connect the project and engine',
            'deployment or model lineage must resolve the requested runtime artifact',
          ],
        },
      ],
    },
  {
      actionId: 'project.deploy.create',
      permissionId: 'project:deploy',
      resourceType: 'project',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Deployments',
      description: 'Deploy a project artifact to an eligible engine target.',
      ui: [{ surfaceId: 'project.deploy.button', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/git-api/deploy', resourceResolver: 'project.byId' },
        {
          method: 'POST',
          route: '/api/projects/:projectId/deployments',
          resourceResolver: 'project.byId',
          openApi: false,
          additionalChecks: ['planned canonical manual deploy route; current public routes use engines-api/git-api deploy endpoints'],
        },
      ],
    },
  {
      actionId: 'project-engine-target.external-registration.upsert',
      permissionId: 'external-engine-system:project-targets:manage',
      resourceType: 'external_engine_system',
      operation: 'sync',
      risk: 'critical',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Register or update a project-engine deployment target through an external source system.',
      ui: [{ surfaceId: 'admin.project-engine-targets.external-api', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/external/project-engine-targets',
          resourceResolver: 'externalEngineSystem.byId',
          additionalChecks: [
            'API client bearer token with engine:register scope is required',
            'API client must have external-engine-system:project-targets:manage for the provided externalSystemId',
            'projectId must reference an existing EnterpriseGlue project',
            'engineId or externalEngineId must resolve to an existing engine owned by the same external system',
            'manual/local targets cannot be silently taken over by an external system',
          ],
        },
      ],
    },
  {
      actionId: 'project-engine-target.external-registration.decommission',
      permissionId: 'external-engine-system:project-targets:manage',
      resourceType: 'external_engine_system',
      operation: 'sync',
      risk: 'critical',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Archive a source-owned project-engine deployment target through an external source system.',
      ui: [{ surfaceId: 'admin.project-engine-targets.external-api.decommission', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/external/project-engine-targets/decommission',
          resourceResolver: 'externalEngineSystem.byId',
          additionalChecks: [
            'API client bearer token with engine:register scope is required',
            'API client must have external-engine-system:project-targets:manage for the provided externalSystemId',
            'only targets previously owned by the same external system can be archived through this API',
          ],
        },
      ],
    },
  {
      actionId: 'project-engine-target.access.request',
      permissionId: 'project:settings:manage',
      resourceType: 'project',
      operation: 'create',
      risk: 'medium',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Request project access to an engine.',
      ui: [{ surfaceId: 'project.engine-access.request', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/engines-api/engines/{engineId}/request-access',
          resourceResolver: 'project.byId',
          additionalChecks: ['projectId comes from request body; legacy project owner/delegate role also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'project-engine-target.deploy.use',
      permissionId: 'project:deploy',
      resourceType: 'project_engine_target',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Deployments',
      description: 'Use an active project-engine target for deployment after project and engine permissions pass.',
      ui: [{ surfaceId: 'project.deploy.engine-selector.option', behavior: 'hide' }],
      routes: [
        {
          method: 'POST',
          route: '/api/projects/:projectId/deployments',
          resourceResolver: 'projectEngineTarget.fromProjectAndEngine',
          openApi: false,
          additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'target.mode.manual'],
        },
        {
          method: 'POST',
          route: '/engines-api/engines/:engineId/deployments/preview',
          resourceResolver: 'projectEngineTarget.fromProjectAndEngine',
          additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'target.mode.manual'],
        },
        {
          method: 'POST',
          route: '/engines-api/engines/:engineId/deployments',
          resourceResolver: 'projectEngineTarget.fromProjectAndEngine',
          additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'target.mode.manual'],
        },
        {
          method: 'POST',
          route: '/git-api/deploy',
          resourceResolver: 'projectEngineTarget.fromProjectAndEngine',
          additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'target.mode.ci'],
        },
        {
          method: 'POST',
          route: '/engines-api/external/engines/:engineId/deployments',
          resourceResolver: 'projectEngineTarget.fromProjectAndEngine',
          additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'target.mode.api', 'api-client.deployment.execute'],
        },
      ],
    },
  {
      actionId: 'project.deployment-options.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Deployments',
      description: 'Read engines connected to a project with deployment eligibility state.',
      ui: [{ surfaceId: 'project.deploy.engine-selector', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/starbase-api/projects/:projectId/engine-access',
          resourceResolver: 'project.byId',
          additionalChecks: ['project.deploy.create', 'engine.deploy.create', 'project-engine-target.deploy.use'],
        },
      ],
    },
  {
      actionId: 'project.deployments.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Deployments',
      description: 'Read project-scoped deployment history and latest deployment metadata.',
      ui: [
        { surfaceId: 'project.deployments.history', behavior: 'hide' },
        { surfaceId: 'project.files.deployment-history', behavior: 'hide' },
      ],
      routes: [
        { method: 'GET', route: '/starbase-api/projects/:projectId/engine-deployments', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/projects/:projectId/engine-deployments/latest', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/projects/:projectId/files/:fileId/deployments', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/projects/:projectId/files/:fileId/deployments/history', resourceResolver: 'project.byId' },
        {
          method: 'GET',
          route: '/git-api/deployments',
          resourceResolver: 'project.byId',
          additionalChecks: ['projectId comes from query string; project permission is rechecked before returning deployment history'],
        },
        { method: 'GET', route: '/git-api/projects/:projectId/deployments', resourceResolver: 'project.byId' },
        {
          method: 'GET',
          route: '/git-api/deployments/:id',
          resourceResolver: 'project.byGitDeploymentId',
          additionalChecks: ['project id is resolved from the Git deployment record before checking project access'],
        },
        {
          method: 'GET',
          route: '/git-api/commits',
          resourceResolver: 'project.byId',
          additionalChecks: ['projectId comes from query string; project permission is rechecked before returning commit history'],
        },
      ],
    },
  {
      actionId: 'project.projects.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Projects',
      description: 'Read the collection of projects visible to the current user.',
      ui: [{ surfaceId: 'starbase.projects.list', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/starbase-api/projects',
          resourceResolver: 'project.visibleCollection',
          additionalChecks: ['collection is filtered to projects where caller is owner or project member'],
        },
      ],
    },
  {
      actionId: 'project.projects.create',
      permissionId: 'project:create',
      resourceType: 'platform',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Projects',
      description: 'Create a new Starbase project, optionally importing latest definitions from an engine.',
      ui: [{ surfaceId: 'starbase.projects.create', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/starbase-api/projects',
          resourceResolver: 'platform.self',
          additionalChecks: ['optional engine import requires engine import preview and import eligibility checks'],
        },
      ],
    },
  {
      actionId: 'project.projects.update',
      permissionId: 'project:settings:manage',
      resourceType: 'project',
      operation: 'update',
      risk: 'medium',
      audit: true,
      category: 'Projects',
      description: 'Rename or update Starbase project settings.',
      ui: [{ surfaceId: 'project.settings.rename', behavior: 'disable' }],
      routes: [{ method: 'PATCH', route: '/starbase-api/projects/{projectId}', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.projects.delete',
      permissionId: 'project:delete',
      resourceType: 'project',
      operation: 'delete',
      risk: 'critical',
      audit: true,
      category: 'Projects',
      description: 'Delete a Starbase project and cascade associated files, folders, and versions.',
      ui: [{ surfaceId: 'project.settings.delete', behavior: 'disable' }],
      routes: [{ method: 'DELETE', route: '/starbase-api/projects/{projectId}', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.members.read',
      permissionId: 'project:members:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Members',
      description: 'Read active and pending project members.',
      ui: [{ surfaceId: 'project.members.list', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/starbase-api/projects/{projectId}/members',
          resourceResolver: 'project.byId',
          additionalChecks: ['legacy project access is also accepted for compatibility'],
        },
      ],
    },
  {
      actionId: 'project.members.search',
      permissionId: 'project:members:search',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Members',
      description: 'Search or look up candidate users for project membership changes.',
      ui: [{ surfaceId: 'project.members.search', behavior: 'disable' }],
      routes: [
        { method: 'GET', route: '/starbase-api/projects/{projectId}/members/user-search', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/projects/{projectId}/members/lookup', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.members.invite',
      permissionId: 'project:members:invite',
      resourceType: 'project',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Project Members',
      description: 'Inspect invite capabilities and manage pending project invitations.',
      ui: [{ surfaceId: 'project.members.invite', behavior: 'disable' }],
      routes: [
        { method: 'GET', route: '/starbase-api/projects/{projectId}/members/capabilities', resourceResolver: 'project.byId' },
        { method: 'POST', route: '/starbase-api/projects/{projectId}/pending-invites/{invitationId}/reissue', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.members.add',
      permissionId: 'project:members:add',
      resourceType: 'project',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Project Members',
      description: 'Add an existing user to a project or invite a pending user through the same endpoint.',
      ui: [{ surfaceId: 'project.members.add', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/starbase-api/projects/{projectId}/members',
          resourceResolver: 'project.byId',
          additionalChecks: [
            'existing users require project:members:add',
            'pending or unknown users require project:members:invite',
            'delegate assignment requires project:delegate:manage',
          ],
        },
      ],
    },
  {
      actionId: 'project.members.update-role',
      permissionId: 'project:members:update-role',
      resourceType: 'project',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Project Members',
      description: 'Update project member roles.',
      ui: [{ surfaceId: 'project.members.role', behavior: 'disable' }],
      routes: [
        {
          method: 'PATCH',
          route: '/starbase-api/projects/{projectId}/members/{userId}',
          resourceResolver: 'project.byId',
          additionalChecks: ['delegate assignment requires project:delegate:manage'],
        },
      ],
    },
  {
      actionId: 'project.members.remove',
      permissionId: 'project:members:remove',
      resourceType: 'project',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Project Members',
      description: 'Remove a user from a project or let the caller remove their own membership.',
      ui: [{ surfaceId: 'project.members.remove', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/starbase-api/projects/{projectId}/members/{userId}',
          resourceResolver: 'project.byId',
          additionalChecks: ['caller may remove self without project:members:remove unless target is owner'],
        },
      ],
    },
  {
      actionId: 'project.members.deploy-grant.manage',
      permissionId: 'project:members:manage-deploy-grant',
      resourceType: 'project',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Project Members',
      description: 'Grant or revoke project deployment permission for members with project file-edit access.',
      ui: [{ surfaceId: 'project.members.deploy-grant', behavior: 'disable' }],
      routes: [
        { method: 'PUT', route: '/starbase-api/projects/{projectId}/members/{userId}/deploy-permission', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.ownership.transfer',
      permissionId: 'project:ownership:transfer',
      resourceType: 'project',
      operation: 'manage',
      risk: 'critical',
      audit: true,
      category: 'Project Members',
      description: 'Transfer Starbase project ownership to another existing member.',
      ui: [{ surfaceId: 'project.members.transfer-ownership', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/starbase-api/projects/{projectId}/transfer-ownership', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.deployment-targets.read',
      permissionId: 'project:deployment-targets:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Engine Targets',
      description: 'Read deployment targets configured for a project.',
      ui: [{ surfaceId: 'project.settings.deployment-targets', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/starbase-api/projects/{projectId}/deployment-targets', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.deployment-targets.manage',
      permissionId: 'project:deployment-targets:manage',
      resourceType: 'project',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Project Engine Targets',
      description: 'Create, update, archive, or reconcile deployment targets for a project.',
      ui: [{ surfaceId: 'project.settings.deployment-targets.edit', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/starbase-api/projects/{projectId}/deployment-targets', resourceResolver: 'project.byId' },
        { method: 'PUT', route: '/starbase-api/projects/{projectId}/deployment-targets/{targetId}', resourceResolver: 'project.byId' },
        { method: 'DELETE', route: '/starbase-api/projects/{projectId}/deployment-targets/{targetId}', resourceResolver: 'project.byId' },
        { method: 'POST', route: '/starbase-api/projects/{projectId}/deployment-targets/sync-legacy', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.files.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Files',
      description: 'Read Starbase project file, folder, comments, and archive content.',
      ui: [
        { surfaceId: 'project.files.list', behavior: 'hide' },
        { surfaceId: 'project.files.detail', behavior: 'hide' },
        { surfaceId: 'project.files.download', behavior: 'hide' },
      ],
      routes: [
        { method: 'GET', route: '/starbase-api/projects/{projectId}/files', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/files/{fileId}', resourceResolver: 'project.byFileId' },
        { method: 'GET', route: '/starbase-api/projects/{projectId}/files/{fileId}/callers', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/files/{fileId}/download', resourceResolver: 'project.byFileId' },
        { method: 'GET', route: '/starbase-api/files/{fileId}/comments', resourceResolver: 'project.byFileId' },
        { method: 'GET', route: '/starbase-api/projects/{projectId}/contents', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/projects/{projectId}/folders', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/starbase-api/folders/{folderId}/download', resourceResolver: 'project.byFolderId' },
        { method: 'GET', route: '/starbase-api/projects/{projectId}/download', resourceResolver: 'project.byId' },
        { method: 'POST', route: '/starbase-api/projects/{projectId}/download-selection', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.files.create',
      permissionId: 'project:files:create',
      resourceType: 'project',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Project Files',
      description: 'Create Starbase project files, folders, or import ZIP archives.',
      ui: [
        { surfaceId: 'project.files.create', behavior: 'disable' },
        { surfaceId: 'project.folders.create', behavior: 'disable' },
        { surfaceId: 'project.files.import-zip', behavior: 'disable' },
      ],
      routes: [
        { method: 'POST', route: '/starbase-api/projects/{projectId}/files', resourceResolver: 'project.byId' },
        { method: 'POST', route: '/starbase-api/projects/{projectId}/folders', resourceResolver: 'project.byId' },
        { method: 'POST', route: '/starbase-api/projects/{projectId}/import-zip', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.files.update',
      permissionId: 'project:files:edit',
      resourceType: 'project',
      operation: 'update',
      risk: 'high',
      audit: true,
      category: 'Project Files',
      description: 'Update Starbase project file XML, file metadata, or folder metadata.',
      ui: [
        { surfaceId: 'project.files.edit', behavior: 'disable' },
        { surfaceId: 'project.folders.edit', behavior: 'disable' },
      ],
      routes: [
        { method: 'PUT', route: '/starbase-api/files/{fileId}', resourceResolver: 'project.byFileId' },
        { method: 'PATCH', route: '/starbase-api/files/{fileId}', resourceResolver: 'project.byFileId' },
        { method: 'PATCH', route: '/starbase-api/folders/{folderId}', resourceResolver: 'project.byFolderId' },
      ],
    },
  {
      actionId: 'project.files.delete',
      permissionId: 'project:files:delete',
      resourceType: 'project',
      operation: 'delete',
      risk: 'high',
      audit: true,
      category: 'Project Files',
      description: 'Delete Starbase project files or folders and preview folder delete impact.',
      ui: [
        { surfaceId: 'project.files.delete', behavior: 'disable' },
        { surfaceId: 'project.folders.delete', behavior: 'disable' },
      ],
      routes: [
        { method: 'DELETE', route: '/starbase-api/files/{fileId}', resourceResolver: 'project.byFileId' },
        { method: 'GET', route: '/starbase-api/folders/{folderId}/delete-preview', resourceResolver: 'project.byFolderId' },
        { method: 'DELETE', route: '/starbase-api/folders/{folderId}', resourceResolver: 'project.byFolderId' },
      ],
    },
  {
      actionId: 'project.files.restore',
      permissionId: 'project:versions:restore',
      resourceType: 'project',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Project Files',
      description: 'Restore a Starbase file from a deployed commit or version snapshot.',
      ui: [{ surfaceId: 'project.files.restore', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/starbase-api/files/{fileId}/restore-from-commit', resourceResolver: 'project.byFileId' },
      ],
    },
  {
      actionId: 'project.versions.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Versions',
      description: 'Read file versions and compare version metadata for visible project files.',
      ui: [{ surfaceId: 'project.versions.list', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/starbase-api/files/{fileId}/versions', resourceResolver: 'project.byFileId' },
        { method: 'GET', route: '/starbase-api/files/{fileId}/versions/{versionId}', resourceResolver: 'project.byFileId' },
        {
          method: 'GET',
          route: '/starbase-api/versions/{versionId}/compare/{otherVersionId}',
          resourceResolver: 'project.byVersionId',
          additionalChecks: ['both compared versions must belong to files visible to the caller'],
        },
      ],
    },
  {
      actionId: 'project.versions.create',
      permissionId: 'project:versions:create',
      resourceType: 'project',
      operation: 'create',
      risk: 'medium',
      audit: true,
      category: 'Project Versions',
      description: 'Create a file version snapshot.',
      ui: [{ surfaceId: 'project.versions.create', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/starbase-api/files/{fileId}/versions', resourceResolver: 'project.byFileId' }],
    },
  {
      actionId: 'project.versions.restore',
      permissionId: 'project:versions:restore',
      resourceType: 'project',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Project Versions',
      description: 'Restore a file from a local version snapshot.',
      ui: [{ surfaceId: 'project.versions.restore', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/starbase-api/files/{fileId}/versions/{versionId}/restore', resourceResolver: 'project.byFileId' }],
    },
  {
      actionId: 'project.vcs.status.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Versions',
      description: 'Read project VCS dirty state, unpublished state, and uncommitted file ids.',
      ui: [{ surfaceId: 'project.vcs.status', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/vcs-api/projects/uncommitted-status',
          resourceResolver: 'project.visibleCollection',
          additionalChecks: ['projectIds query is filtered to projects the caller owns, can access, or has project:files:view for'],
        },
        { method: 'GET', route: '/vcs-api/projects/{projectId}/status', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/vcs-api/projects/{projectId}/uncommitted-files', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.vcs.commits.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Versions',
      description: 'Read project VCS commit history and commit file snapshots.',
      ui: [
        { surfaceId: 'project.vcs.commits', behavior: 'hide' },
        { surfaceId: 'project.vcs.commit-files', behavior: 'hide' },
      ],
      routes: [
        { method: 'GET', route: '/vcs-api/projects/{projectId}/commits', resourceResolver: 'project.byId' },
        { method: 'GET', route: '/vcs-api/projects/{projectId}/commits/{commitId}/files', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.vcs.commit.create',
      permissionId: 'project:versions:create',
      resourceType: 'project',
      operation: 'create',
      risk: 'medium',
      audit: true,
      category: 'Project Versions',
      description: 'Create a project VCS checkpoint from the caller draft branch.',
      ui: [{ surfaceId: 'project.vcs.commit.create', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/vcs-api/projects/{projectId}/commit', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.vcs.publish',
      permissionId: 'project:versions:create',
      resourceType: 'project',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Project Versions',
      description: 'Publish the caller draft branch into the project main branch.',
      ui: [{ surfaceId: 'project.vcs.publish', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/vcs-api/projects/{projectId}/publish', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.vcs.commit.restore',
      permissionId: 'project:versions:restore',
      resourceType: 'project',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Project Versions',
      description: 'Restore project files from a VCS checkpoint and create a restore checkpoint.',
      ui: [{ surfaceId: 'project.vcs.commit.restore', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/vcs-api/projects/{projectId}/commits/{commitId}/restore', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.import.preview',
      permissionId: 'engine:deploy:view',
      resourceType: 'engine',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Project Import',
      description: 'Preview latest BPMN and DMN definitions available for import from an engine during project creation.',
      ui: [{ surfaceId: 'project.create.import-engine-preview', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/starbase-api/projects/import-preview', resourceResolver: 'engine.byId' }],
    },
  {
      actionId: 'project.create.git.inspect',
      permissionId: 'project:create',
      resourceType: 'platform',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Git',
      description: 'Inspect remote Git repository metadata during project creation with the caller-owned Git credential.',
      ui: [{ surfaceId: 'project.create.git.remote-inspection', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/git-api/repo-info',
          resourceResolver: 'platform.self',
          additionalChecks: ['current-user Git credential must exist for the selected provider'],
        },
        {
          method: 'POST',
          route: '/git-api/check-repo-exists',
          resourceResolver: 'platform.self',
          additionalChecks: ['current-user Git credential or request token must authorize the remote repository lookup'],
        },
      ],
    },
  {
      actionId: 'project.create.git.create',
      permissionId: 'project:create',
      resourceType: 'platform',
      operation: 'create',
      risk: 'high',
      audit: true,
      category: 'Git',
      description: 'Create a local project from a remote Git repository or create a remote repository for a new project.',
      ui: [{ surfaceId: 'project.create.git.submit', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/git-api/clone',
          resourceResolver: 'platform.self',
          additionalChecks: ['current-user Git credential must authorize repository read; created project receives caller as owner'],
        },
        {
          method: 'POST',
          route: '/git-api/create-online',
          resourceResolver: 'platform.self',
          additionalChecks: ['current-user Git credential or request token must authorize remote repository create; optional engine import must pass engine import permission'],
        },
      ],
    },
  {
      actionId: 'project.git.repositories.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Git',
      description: 'Read project Git repository metadata and project Git connection state.',
      ui: [
        { surfaceId: 'project.git.repositories', behavior: 'hide' },
        { surfaceId: 'project.git.connection.status', behavior: 'hide' },
      ],
      routes: [
        {
          method: 'GET',
          route: '/git-api/repositories',
          resourceResolver: 'project.visibleCollection',
          additionalChecks: ['projectId may come from query string; collection responses are filtered by project permission'],
        },
        {
          method: 'GET',
          route: '/git-api/repositories/:id',
          resourceResolver: 'project.byGitRepositoryId',
          additionalChecks: ['project id is resolved from the Git repository record before checking project access'],
        },
        {
          method: 'GET',
          route: '/git-api/project-connection',
          resourceResolver: 'project.byId',
          additionalChecks: ['projectId comes from query string; project permission is rechecked before returning connection state'],
        },
      ],
    },
  {
      actionId: 'project.git.repositories.manage',
      permissionId: 'project:git:connect',
      resourceType: 'project',
      operation: 'manage',
      risk: 'high',
      audit: true,
      category: 'Git',
      description: 'Initialize, clone, connect, update, disconnect, or remove a project Git repository connection.',
      ui: [{ surfaceId: 'project.git.connection.manage', behavior: 'disable' }],
      routes: [
        { method: 'POST', route: '/git-api/repositories/init', resourceResolver: 'project.byId' },
        { method: 'POST', route: '/git-api/repositories/clone', resourceResolver: 'project.byId' },
        {
          method: 'DELETE',
          route: '/git-api/repositories/:id',
          resourceResolver: 'project.byGitRepositoryId',
          additionalChecks: ['project id is resolved from the Git repository record before checking project access'],
        },
        { method: 'POST', route: '/git-api/project-connection', resourceResolver: 'project.byId' },
        { method: 'PUT', route: '/git-api/project-connection/token', resourceResolver: 'project.byId' },
        { method: 'DELETE', route: '/git-api/project-connection', resourceResolver: 'project.byId' },
      ],
    },
  {
      actionId: 'project.git.sync.status',
      permissionId: 'project:git:pull',
      resourceType: 'project',
      operation: 'read',
      risk: 'medium',
      audit: false,
      category: 'Git',
      description: 'Read project Git sync status.',
      ui: [{ surfaceId: 'project.git.sync.status', behavior: 'hide' }],
      routes: [
        {
          method: 'GET',
          route: '/git-api/sync/status',
          resourceResolver: 'project.byId',
          additionalChecks: ['project:git:push is also accepted for status'],
        },
      ],
    },
  {
      actionId: 'project.git.sync.run',
      permissionId: 'project:git:push',
      resourceType: 'project',
      operation: 'sync',
      risk: 'high',
      audit: true,
      category: 'Git',
      description: 'Run project Git push, pull, or bidirectional sync.',
      ui: [{ surfaceId: 'project.git.sync.action', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/git-api/sync',
          resourceResolver: 'project.byId',
          additionalChecks: ['project:git:pull required for pull/both directions'],
        },
      ],
    },
  {
      actionId: 'project.git.rollback',
      permissionId: 'project:versions:restore',
      resourceType: 'project',
      operation: 'execute',
      risk: 'high',
      audit: true,
      category: 'Git',
      description: 'Roll back a project to a Git commit.',
      ui: [{ surfaceId: 'project.git.rollback', behavior: 'disable' }],
      routes: [{ method: 'POST', route: '/git-api/rollback', resourceResolver: 'project.byId' }],
    },
  {
      actionId: 'project.git.locks.read',
      permissionId: 'project:files:view',
      resourceType: 'project',
      operation: 'read',
      risk: 'low',
      audit: false,
      category: 'Git',
      description: 'Read project file lock state and lock-event streams.',
      ui: [{ surfaceId: 'project.files.locks', behavior: 'hide' }],
      routes: [
        { method: 'GET', route: '/git-api/locks', resourceResolver: 'project.byId' },
        {
          method: 'GET',
          route: '/git-api/locks/:fileId/events',
          resourceResolver: 'project.byFileId',
          additionalChecks: ['project id is resolved from the file record before opening the event stream'],
        },
      ],
    },
  {
      actionId: 'project.git.locks.acquire',
      permissionId: 'project:files:edit',
      resourceType: 'project',
      operation: 'manage',
      risk: 'medium',
      audit: true,
      category: 'Git',
      description: 'Acquire or force-take over a project file lock.',
      ui: [{ surfaceId: 'project.files.lock.acquire', behavior: 'disable' }],
      routes: [
        {
          method: 'POST',
          route: '/git-api/locks',
          resourceResolver: 'project.byFileId',
          additionalChecks: ['project id is resolved from the requested file id before checking file edit permission'],
        },
      ],
    },
  {
      actionId: 'project.git.locks.release',
      permissionId: 'project:files:edit',
      resourceType: 'project',
      operation: 'manage',
      risk: 'medium',
      audit: true,
      category: 'Git',
      description: 'Release a project file lock.',
      ui: [{ surfaceId: 'project.files.lock.release', behavior: 'disable' }],
      routes: [
        {
          method: 'DELETE',
          route: '/git-api/locks/:lockId',
          resourceResolver: 'project.byGitLockId',
          additionalChecks: ['lock holder may release own lock; project:settings:manage may release another user lock'],
        },
      ],
    },
  {
      actionId: 'project.git.locks.heartbeat',
      permissionId: 'project:files:edit',
      resourceType: 'project',
      operation: 'manage',
      risk: 'low',
      audit: false,
      category: 'Git',
      description: 'Renew a project file lock owned by the caller.',
      ui: [{ surfaceId: 'project.files.lock.heartbeat', behavior: 'disable' }],
      routes: [
        {
          method: 'PUT',
          route: '/git-api/locks/:lockId/heartbeat',
          resourceResolver: 'project.byGitLockId',
          additionalChecks: ['caller must be the current lock holder'],
        },
      ],
    },
] satisfies AuthzActionDefinition[];
