import type { AuthzActionDefinition } from '../permission-actions.js';

export const TENANT_AUTHZ_ACTIONS = [
  {
    actionId: 'tenant.settings.read',
    permissionId: 'tenant:settings:view',
    resourceType: 'tenant',
    operation: 'read',
    risk: 'medium',
    audit: false,
    category: 'Tenant Administration',
    description: 'Read the current tenant profile and non-secret settings.',
    ui: [{ surfaceId: 'tenant.settings', behavior: 'hide' }],
    routes: [{ method: 'GET', route: '/api/t/{tenantSlug}/tenant', resourceResolver: 'tenant.fromContext' }],
  },
  {
    actionId: 'tenant.settings.manage',
    permissionId: 'tenant:settings:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'high',
    audit: true,
    category: 'Tenant Administration',
    description: 'Manage the current tenant login policy and verified domains.',
    ui: [{ surfaceId: 'tenant.settings.actions', behavior: 'disable' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/login-policy', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/tenant/login-policy', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/domains/{domainId}/verify', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/discovery-domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/discovery-domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/discovery-domains/{domainId}/verify', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/api/t/{tenantSlug}/tenant/discovery-domains/{domainId}', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.members.manage',
    permissionId: 'tenant:members:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'critical',
    audit: true,
    category: 'Tenant Administration',
    description: 'Read or change membership in the current tenant.',
    ui: [{ surfaceId: 'tenant.members', behavior: 'disable' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/members', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/tenant/members/{userId}', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/api/t/{tenantSlug}/tenant/members/{userId}', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.sso.providers.read',
    permissionId: 'tenant:sso-providers:view',
    resourceType: 'tenant',
    operation: 'read',
    risk: 'high',
    audit: false,
    category: 'Tenant Identity',
    description: 'Read the current tenant identity providers and sanitized reconciliation history.',
    ui: [{ surfaceId: 'tenant.sso.providers', behavior: 'hide' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}/sync-runs', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}/sync-runs/{runId}/events', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}/sync-runs', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}/sync-runs/{runId}/events', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.sso.providers.manage',
    permissionId: 'tenant:sso-providers:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'critical',
    audit: true,
    category: 'Tenant Identity',
    description: 'Create, update, test, reconcile, or archive identity providers in the current tenant.',
    ui: [{ surfaceId: 'tenant.sso.providers.actions', behavior: 'disable' }],
    routes: [
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/external-identities/unlink', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/api/t/{tenantSlug}/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/reconcile', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/reconciliation-preview', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/replay-memberships', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/test-connection', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/external-identities/unlink', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/t/{tenantSlug}/api/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/t/{tenantSlug}/api/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/reconcile', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/reconciliation-preview', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/replay-memberships', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/test-connection', resourceResolver: 'tenant.fromContext' },
    ],
  },
] satisfies AuthzActionDefinition[];
