import type { AuthzActionDefinition } from '../permission-actions.js';

export const TENANT_AUTHZ_ACTIONS = [
  {
    actionId: 'tenant.apps.read',
    permissionId: 'tenant:apps:view',
    resourceType: 'tenant',
    operation: 'read',
    risk: 'low',
    audit: false,
    category: 'Tenant Applications',
    description: 'Read the safe application catalogue and lifecycle state for the current tenant.',
    ui: [{ surfaceId: 'tenant.apps', behavior: 'hide' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/apps', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/apps/{pluginId}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/apps/{pluginId}/configuration', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/apps/{pluginId}/audit', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/plugin-platform/v1/plugins/{pluginId}/enablement', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/plugin-platform/v1/plugins/{pluginId}/enablement', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.apps.request',
    permissionId: 'tenant:apps:request',
    resourceType: 'tenant',
    operation: 'create',
    risk: 'medium',
    audit: true,
    category: 'Tenant Applications',
    description: 'Request activation of an available application for the current tenant.',
    ui: [{ surfaceId: 'tenant.apps.request', behavior: 'disable' }],
    routes: [
      { method: 'POST', route: '/api/t/{tenantSlug}/apps/{pluginId}/activation-request', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.apps.manage',
    permissionId: 'tenant:apps:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'high',
    audit: true,
    category: 'Tenant Applications',
    description: 'Activate, deactivate, or decide application requests only for the current tenant.',
    ui: [{ surfaceId: 'tenant.apps.actions', behavior: 'disable' }],
    routes: [
      { method: 'POST', route: '/api/t/{tenantSlug}/apps/{pluginId}/activate', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/apps/{pluginId}/deactivate', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/apps/{pluginId}/activation-request/decision', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/plugin-platform/v1/plugins/{pluginId}/enablement', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/t/{tenantSlug}/api/plugin-platform/v1/plugins/{pluginId}/enablement', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.apps.use',
    permissionId: 'tenant:apps:use',
    resourceType: 'tenant',
    operation: 'execute',
    risk: 'medium',
    audit: false,
    category: 'Tenant Applications',
    description: 'Use active application contributions in the current tenant.',
    ui: [{ surfaceId: 'tenant.apps.runtime', behavior: 'hide' }],
  },
  {
    actionId: 'tenant.settings.read',
    permissionId: 'tenant:settings:view',
    resourceType: 'tenant',
    operation: 'read',
    risk: 'medium',
    audit: false,
    category: 'Tenant Administration',
    description: 'Read the current tenant profile and non-secret settings.',
    ui: [{ surfaceId: 'tenant.settings', behavior: 'hide' }],
    routes: [{ method: 'GET', route: '/api/t/{tenantSlug}/tenant', resourceResolver: 'tenant.fromContext' }],
  },
  {
    actionId: 'tenant.settings.manage',
    permissionId: 'tenant:settings:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'high',
    audit: true,
    category: 'Tenant Administration',
    description: 'Manage the current tenant login policy and verified domains.',
    ui: [{ surfaceId: 'tenant.settings.actions', behavior: 'disable' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/login-policy', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/tenant/login-policy', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/domains/{domainId}/verify', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/discovery-domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/discovery-domains', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/tenant/discovery-domains/{domainId}/verify', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/api/t/{tenantSlug}/tenant/discovery-domains/{domainId}', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.members.manage',
    permissionId: 'tenant:members:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'critical',
    audit: true,
    category: 'Tenant Administration',
    description: 'Read or change membership in the current tenant.',
    ui: [{ surfaceId: 'tenant.members', behavior: 'disable' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/tenant/members', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/tenant/members/{userId}', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/api/t/{tenantSlug}/tenant/members/{userId}', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.sso.providers.read',
    permissionId: 'tenant:sso-providers:view',
    resourceType: 'tenant',
    operation: 'read',
    risk: 'high',
    audit: false,
    category: 'Tenant Identity',
    description: 'Read the current tenant identity providers and sanitized reconciliation history.',
    ui: [{ surfaceId: 'tenant.sso.providers', behavior: 'hide' }],
    routes: [
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}/sync-runs', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}/sync-runs/{runId}/events', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}/sync-runs', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}/sync-runs/{runId}/events', resourceResolver: 'tenant.fromContext' },
    ],
  },
  {
    actionId: 'tenant.sso.providers.manage',
    permissionId: 'tenant:sso-providers:manage',
    resourceType: 'tenant',
    operation: 'manage',
    risk: 'critical',
    audit: true,
    category: 'Tenant Identity',
    description: 'Create, update, test, reconcile, or archive identity providers in the current tenant.',
    ui: [{ surfaceId: 'tenant.sso.providers.actions', behavior: 'disable' }],
    routes: [
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/provider-secrets', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/provider-secrets/retire', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/external-identities/unlink', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/identity/providers/{key}/secrets/{purpose}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/api/t/{tenantSlug}/identity/providers/{key}/secrets/{purpose}/availability', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/secrets/{purpose}/retire', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/api/t/{tenantSlug}/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/api/t/{tenantSlug}/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/reconcile', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/reconciliation-preview', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/replay-memberships', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/api/t/{tenantSlug}/identity/providers/{key}/test-connection', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/provider-secrets', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/provider-secrets/retire', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/external-identities/unlink', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/t/{tenantSlug}/api/identity/providers/{key}/secrets/{purpose}', resourceResolver: 'tenant.fromContext' },
      { method: 'GET', route: '/t/{tenantSlug}/api/identity/providers/{key}/secrets/{purpose}/availability', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/secrets/{purpose}/retire', resourceResolver: 'tenant.fromContext' },
      { method: 'PUT', route: '/t/{tenantSlug}/api/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'DELETE', route: '/t/{tenantSlug}/api/identity/providers/{key}', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/reconcile', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/reconciliation-preview', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/replay-memberships', resourceResolver: 'tenant.fromContext' },
      { method: 'POST', route: '/t/{tenantSlug}/api/identity/providers/{key}/test-connection', resourceResolver: 'tenant.fromContext' },
    ],
  },
] satisfies AuthzActionDefinition[];
