apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterpriseglue-plugin-installer
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
