import { describe, expect, it } from 'vitest';
import { AddIdentityProviders1700000000056 as DbIdentityProvidersMigration } from '@enterpriseglue/shared/db/migrations/1700000000056-add-identity-providers.js';
import { AddIdentityReconciliationAndDeploymentReceipts1700000000057 as DbReconciliationMigration } from '@enterpriseglue/shared/db/migrations/1700000000057-add-identity-reconciliation-and-deployment-receipts.js';
import { AddIdentityProviders1700000000056 as PersistenceIdentityProvidersMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000056-add-identity-providers.js';
import { AddIdentityReconciliationAndDeploymentReceipts1700000000057 as PersistenceReconciliationMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000057-add-identity-reconciliation-and-deployment-receipts.js';
import { DropLegacySsoMappingTables1700000000089 as DbDropLegacyMappingsMigration } from '@enterpriseglue/shared/db/migrations/1700000000089-drop-legacy-sso-mapping-tables.js';
import { DropLegacySsoMappingTables1700000000089 as PersistenceDropLegacyMappingsMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000089-drop-legacy-sso-mapping-tables.js';
import { DropLegacySsoProviders1700000000090 as DbDropLegacyProvidersMigration } from '@enterpriseglue/shared/db/migrations/1700000000090-drop-legacy-sso-providers.js';
import { DropLegacySsoProviders1700000000090 as PersistenceDropLegacyProvidersMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000090-drop-legacy-sso-providers.js';
import { FinalizeLegacyRoleAssignmentProjections1700000000091 as DbFinalizeLegacyRoleAssignmentsMigration } from '@enterpriseglue/shared/db/migrations/1700000000091-finalize-legacy-role-assignment-projections.js';
import { FinalizeLegacyRoleAssignmentProjections1700000000091 as PersistenceFinalizeLegacyRoleAssignmentsMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000091-finalize-legacy-role-assignment-projections.js';
import { DropLegacyUserIdentityColumns1700000000092 as DbDropLegacyUserIdentityColumnsMigration } from '@enterpriseglue/shared/db/migrations/1700000000092-drop-legacy-user-identity-columns.js';
import { DropLegacyUserIdentityColumns1700000000092 as PersistenceDropLegacyUserIdentityColumnsMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000092-drop-legacy-user-identity-columns.js';
import { DropRoleAssignmentSourceMappingAlias1700000000093 as DbDropRoleAssignmentSourceMappingAliasMigration } from '@enterpriseglue/shared/db/migrations/1700000000093-drop-role-assignment-source-mapping-alias.js';
import { DropRoleAssignmentSourceMappingAlias1700000000093 as PersistenceDropRoleAssignmentSourceMappingAliasMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000093-drop-role-assignment-source-mapping-alias.js';
import { DropRoleAssignmentResourceAliases1700000000094 as DbDropRoleAssignmentResourceAliasesMigration } from '@enterpriseglue/shared/db/migrations/1700000000094-drop-role-assignment-resource-aliases.js';
import { DropRoleAssignmentResourceAliases1700000000094 as PersistenceDropRoleAssignmentResourceAliasesMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000094-drop-role-assignment-resource-aliases.js';
import { DropRoleAssignmentUserAlias1700000000095 as DbDropRoleAssignmentUserAliasMigration } from '@enterpriseglue/shared/db/migrations/1700000000095-drop-role-assignment-user-alias.js';
import { DropRoleAssignmentUserAlias1700000000095 as PersistenceDropRoleAssignmentUserAliasMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000095-drop-role-assignment-user-alias.js';
import { AddEngineTenancyFoundation1700000000096 as DbEngineTenancyFoundationMigration } from '@enterpriseglue/shared/db/migrations/1700000000096-add-engine-tenancy-foundation.js';
import { AddEngineTenancyFoundation1700000000096 as PersistenceEngineTenancyFoundationMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000096-add-engine-tenancy-foundation.js';
import { AddEngineTenantMappingReference1700000000097 as DbEngineTenantMappingReferenceMigration } from '@enterpriseglue/shared/db/migrations/1700000000097-add-engine-tenant-mapping-reference.js';
import { AddEngineTenantMappingReference1700000000097 as PersistenceEngineTenantMappingReferenceMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000097-add-engine-tenant-mapping-reference.js';
import { AddCamundaNativeGrantImportRuns1700000000098 as DbCamundaNativeGrantImportRunsMigration } from '@enterpriseglue/shared/db/migrations/1700000000098-add-camunda-native-grant-import-runs.js';
import { AddCamundaNativeGrantImportRuns1700000000098 as PersistenceCamundaNativeGrantImportRunsMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000098-add-camunda-native-grant-import-runs.js';
import { WidenCamundaNativeGrantEvidence1700000000100 as DbCamundaNativeGrantEvidenceMigration } from '@enterpriseglue/shared/db/migrations/1700000000100-widen-camunda-native-grant-evidence.js';
import { WidenCamundaNativeGrantEvidence1700000000100 as PersistenceCamundaNativeGrantEvidenceMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000100-widen-camunda-native-grant-evidence.js';
import { AddCamundaNativeGrantRollbackReceipt1700000000099 as DbCamundaNativeGrantRollbackReceiptMigration } from '@enterpriseglue/shared/db/migrations/1700000000099-add-camunda-native-grant-rollback-receipt.js';
import { AddCamundaNativeGrantRollbackReceipt1700000000099 as PersistenceCamundaNativeGrantRollbackReceiptMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000099-add-camunda-native-grant-rollback-receipt.js';
import { AddEngineBackstopFoundation1700000000101 as DbEngineBackstopFoundationMigration } from '@enterpriseglue/shared/db/migrations/1700000000101-add-engine-backstop-foundation.js';
import { AddEngineBackstopFoundation1700000000101 as PersistenceEngineBackstopFoundationMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000101-add-engine-backstop-foundation.js';
import { AddEngineBackstopDriftObservations1700000000102 as DbEngineBackstopDriftObservationsMigration } from '@enterpriseglue/shared/db/migrations/1700000000102-add-engine-backstop-drift-observations.js';
import { AddEngineBackstopDriftObservations1700000000102 as PersistenceEngineBackstopDriftObservationsMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000102-add-engine-backstop-drift-observations.js';
import { AddIdentityMappingOwnershipMode1700000000104 as DbIdentityMappingOwnershipMigration } from '@enterpriseglue/shared/db/migrations/1700000000104-add-identity-mapping-ownership-mode.js';
import { AddIdentityMappingOwnershipMode1700000000104 as PersistenceIdentityMappingOwnershipMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000104-add-identity-mapping-ownership-mode.js';
import { AddPlatformGovernanceSettingsOwnership1700000000105 as DbPlatformGovernanceOwnershipMigration } from '@enterpriseglue/shared/db/migrations/1700000000105-add-platform-governance-settings-ownership.js';
import { AddPlatformGovernanceSettingsOwnership1700000000105 as PersistencePlatformGovernanceOwnershipMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000105-add-platform-governance-settings-ownership.js';
import { AddLoginExperienceMetadata1700000000106 as DbLoginExperienceMigration } from '@enterpriseglue/shared/db/migrations/1700000000106-add-login-experience-metadata.js';
import { AddLoginExperienceMetadata1700000000106 as PersistenceLoginExperienceMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000106-add-login-experience-metadata.js';
import { ConsolidateLoginProviderPreference1700000000107 as DbLoginProviderPreferenceMigration } from '@enterpriseglue/shared/db/migrations/1700000000107-consolidate-login-provider-preference.js';
import { ConsolidateLoginProviderPreference1700000000107 as PersistenceLoginProviderPreferenceMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000107-consolidate-login-provider-preference.js';
import { AddIdentityProvisioningFoundation1700000000111 as DbIdentityProvisioningFoundationMigration } from '@enterpriseglue/shared/db/migrations/1700000000111-add-identity-provisioning-foundation.js';
import { AddIdentityProvisioningFoundation1700000000111 as PersistenceIdentityProvisioningFoundationMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000111-add-identity-provisioning-foundation.js';
import { AddFederatedSessionLineage1700000000112 as DbFederatedSessionLineageMigration } from '@enterpriseglue/shared/db/migrations/1700000000112-add-federated-session-lineage.js';
import { AddFederatedSessionLineage1700000000112 as PersistenceFederatedSessionLineageMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000112-add-federated-session-lineage.js';
import { AddProvisioningCredentialIdempotency1700000000113 as DbProvisioningCredentialIdempotencyMigration } from '@enterpriseglue/shared/db/migrations/1700000000113-add-provisioning-credential-idempotency.js';
import { AddProvisioningCredentialIdempotency1700000000113 as PersistenceProvisioningCredentialIdempotencyMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000113-add-provisioning-credential-idempotency.js';
import { AddTenantApplicationMarketplace1700000000128 as DbTenantApplicationMarketplaceMigration } from '@enterpriseglue/shared/db/migrations/1700000000128-add-tenant-application-marketplace.js';
import { AddTenantApplicationMarketplace1700000000128 as PersistenceTenantApplicationMarketplaceMigration } from '@enterpriseglue/shared/infrastructure/persistence/migrations/1700000000128-add-tenant-application-marketplace.js';

describe('persistence migration bridges', () => {
  it('re-exports the identity-provider and deployment-receipt migrations from the canonical persistence path', () => {
    expect(PersistenceIdentityProvidersMigration).toBe(DbIdentityProvidersMigration);
    expect(PersistenceReconciliationMigration).toBe(DbReconciliationMigration);
    expect(PersistenceDropLegacyMappingsMigration).toBe(DbDropLegacyMappingsMigration);
    expect(PersistenceDropLegacyProvidersMigration).toBe(DbDropLegacyProvidersMigration);
    expect(PersistenceFinalizeLegacyRoleAssignmentsMigration).toBe(DbFinalizeLegacyRoleAssignmentsMigration);
    expect(PersistenceDropLegacyUserIdentityColumnsMigration).toBe(DbDropLegacyUserIdentityColumnsMigration);
    expect(PersistenceDropRoleAssignmentSourceMappingAliasMigration).toBe(DbDropRoleAssignmentSourceMappingAliasMigration);
    expect(PersistenceDropRoleAssignmentResourceAliasesMigration).toBe(DbDropRoleAssignmentResourceAliasesMigration);
    expect(PersistenceDropRoleAssignmentUserAliasMigration).toBe(DbDropRoleAssignmentUserAliasMigration);
    expect(PersistenceEngineTenancyFoundationMigration).toBe(DbEngineTenancyFoundationMigration);
    expect(PersistenceEngineTenantMappingReferenceMigration).toBe(DbEngineTenantMappingReferenceMigration);
    expect(PersistenceCamundaNativeGrantImportRunsMigration).toBe(DbCamundaNativeGrantImportRunsMigration);
    expect(PersistenceCamundaNativeGrantEvidenceMigration).toBe(DbCamundaNativeGrantEvidenceMigration);
    expect(PersistenceCamundaNativeGrantRollbackReceiptMigration).toBe(DbCamundaNativeGrantRollbackReceiptMigration);
    expect(PersistenceEngineBackstopFoundationMigration).toBe(DbEngineBackstopFoundationMigration);
    expect(PersistenceEngineBackstopDriftObservationsMigration).toBe(DbEngineBackstopDriftObservationsMigration);
    expect(PersistenceIdentityMappingOwnershipMigration).toBe(DbIdentityMappingOwnershipMigration);
    expect(PersistencePlatformGovernanceOwnershipMigration).toBe(DbPlatformGovernanceOwnershipMigration);
    expect(PersistenceLoginExperienceMigration).toBe(DbLoginExperienceMigration);
    expect(PersistenceLoginProviderPreferenceMigration).toBe(DbLoginProviderPreferenceMigration);
    expect(PersistenceIdentityProvisioningFoundationMigration).toBe(DbIdentityProvisioningFoundationMigration);
    expect(PersistenceFederatedSessionLineageMigration).toBe(DbFederatedSessionLineageMigration);
    expect(PersistenceProvisioningCredentialIdempotencyMigration).toBe(DbProvisioningCredentialIdempotencyMigration);
    expect(PersistenceTenantApplicationMarketplaceMigration).toBe(DbTenantApplicationMarketplaceMigration);
  });
});
