import { vi } from 'vitest';
import type {
  AuthzAuditEntry,
  AuthzGroup,
  AuthzGroupMembership,
  AuthzPolicy,
  EngineSetSummary,
  EffectiveAccessResult,
  ExternalEngineRegistration,
  PermissionCatalogEntry,
  ProjectEngineTarget,
  RoleAssignment,
  RoleSummary,
  SsoClaimsMapping,
  SsoGroupMapping,
  SsoAssignmentMapping,
  SsoSyncEvent,
  SsoSyncRun,
} from '@src/features/platform-admin/hooks/useAuthzApi';
import type { CurrentUserPermissions } from '@src/shared/types/auth';

vi.setConfig({ testTimeout: 60000 });

const ssoAssignmentTestState = vi.hoisted(() => ({
  data: null as null | {
    matchedMappings: Array<SsoAssignmentMapping & { targetResourceId: string | null; targetResourceIds: Array<string | null> }>;
    assignments: Array<{ roleId: string; resourceType: 'engine'; resourceId: string | null; mappingId: string }>;
  },
}));

const evaluateAccessState = vi.hoisted(() => ({
  data: null as EffectiveAccessResult | null,
}));

const authState = vi.hoisted(() => ({
  permissions: {
    userId: 'admin-1',
    platform: [
      'platform:authz:roles:view',
      'platform:authz:roles:manage',
      'platform:authz:check',
      'platform:settings:manage',
      'platform:sso-assignments:view',
      'platform:sso-assignments:manage',
      'platform:engine-sets:view',
      'platform:engine-sets:manage',
      'platform:project-engine-targets:view',
      'platform:project-engine-targets:manage',
      'platform:engine-registration:manage',
      'platform:audit:view',
    ],
    projects: [],
    engines: [],
    generatedAt: 1,
  } as CurrentUserPermissions,
}));

const createRole = vi.fn();
const createPermission = vi.fn();
const createGroup = vi.fn();
const updateGroup = vi.fn();
const archiveGroup = vi.fn();
const addGroupMembership = vi.fn();
const removeGroupMembership = vi.fn();
const updateRole = vi.fn();
const archiveRole = vi.fn();
const assignRole = vi.fn();
const removeAssignment = vi.fn();
const createEngineSet = vi.fn();
const updateEngineSet = vi.fn();
const archiveEngineSet = vi.fn();
const previewEngineSetSelector = vi.fn();
const resetPreviewEngineSetSelector = vi.fn();
const materializeEngineSet = vi.fn();
const createProjectEngineTarget = vi.fn();
const updateProjectEngineTarget = vi.fn();
const archiveProjectEngineTarget = vi.fn();
const syncLegacyProjectEngineTargets = vi.fn();
const evaluateDeploymentEligibility = vi.fn();
const createPolicy = vi.fn();
const updatePolicy = vi.fn();
const deletePolicy = vi.fn();
const createApiClient = vi.fn();
const rotateApiClient = vi.fn();
const revokeApiClient = vi.fn();
const createServiceAccount = vi.fn();
const rotateServiceAccount = vi.fn();
const revokeServiceAccount = vi.fn();
const createExternalSystem = vi.fn();
const updateExternalSystem = vi.fn();
const archiveExternalSystem = vi.fn();
const decommissionExternalEngine = vi.fn();
const reactivateExternalEngine = vi.fn();
const reconcileExternalEngine = vi.fn();
const createSsoPlatformMapping = vi.fn();
const updateSsoPlatformMapping = vi.fn();
const deleteSsoPlatformMapping = vi.fn();
const testSsoPlatformMapping = vi.fn();
const createSsoGroupMapping = vi.fn();
const updateSsoGroupMapping = vi.fn();
const deleteSsoGroupMapping = vi.fn();
const testSsoGroupMapping = vi.fn();
const createSsoAssignment = vi.fn();
const updateSsoAssignment = vi.fn();
const deleteSsoAssignment = vi.fn();
const testSsoAssignment = vi.fn();
const runSsoSyncDiagnostics = vi.fn();
const previewEngineAccessTransitionCleanup = vi.fn();
const applyEngineAccessTransitionCleanup = vi.fn();
const evaluateAccess = vi.fn();
const systemPlatformAdminRoleDetail = {
  id: 'system.platform.admin',
  key: 'system.platform.admin',
  name: 'Platform Admin',
  description: 'Admin',
  scope: 'platform',
  kind: 'system',
  isEditable: false,
  isAssignable: true,
  isArchived: false,
  permissionCount: 2,
  permissions: ['platform:authz:check', 'platform:users:permanent-delete'],
  createdAt: 1,
  updatedAt: 1,
};

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn(),
  })),
});

vi.mock('@src/features/platform-admin/hooks/useAuthzApi', () => ({
  usePermissionCatalog: () => ({
    data: [
      { key: 'platform:authz:check', scope: 'platform', category: 'Access Control', label: 'Check Access', description: 'Check access' },
      { key: 'platform:users:permanent-delete', scope: 'platform', category: 'User Management', label: 'Permanent Delete Users', description: 'Permanently delete users' },
      { key: 'platform:audit:unredacted-view', scope: 'platform', category: 'Audit', label: 'View Unredacted Audit', description: 'View unredacted audit payloads' },
      { key: 'engine:deploy', scope: 'engine', category: 'Engine', label: 'Deploy', description: 'Deploy to engine' },
      { key: 'engine:instance:view', scope: 'engine', category: 'Engine', label: 'View Instances', description: 'View instances' },
    ],
    isLoading: false,
    isError: false,
  }),
  useRbacRoles: () => ({
    data: [
      {
        id: 'system.platform.admin',
        key: 'system.platform.admin',
        name: 'Platform Admin',
        description: 'Admin',
        scope: 'platform',
        kind: 'system',
        isEditable: false,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'custom.engine.operator',
        key: 'custom.engine.operator',
        name: 'Custom Operator',
        description: 'Custom',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 2,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'custom.engine.secret-reader',
        key: 'custom.engine.secret-reader',
        name: 'Custom Secret Reader',
        description: 'Secret reader',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'custom.engine.audit-reader',
        key: 'custom.engine.audit-reader',
        name: 'Custom Audit Reader',
        description: 'Unredacted audit reader',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'custom.engine.permanent-delete',
        key: 'custom.engine.permanent-delete',
        name: 'Custom Permanent Delete',
        description: 'Permanent delete authority',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'system.project.deployer',
        key: 'system.project.deployer',
        name: 'Project Deployer',
        description: 'Deploy only',
        scope: 'project',
        kind: 'system',
        isEditable: false,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'system.api.external_engine_system_registrar',
        key: 'system.api.external_engine_system_registrar',
        name: 'API External System Registrar',
        description: 'External system scoped registrar',
        scope: 'external_engine_system',
        kind: 'system',
        isEditable: false,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'system.engine.deployer',
        key: 'system.engine.deployer',
        name: 'Engine Deployer',
        description: 'Deploy to engine',
        scope: 'engine',
        kind: 'system',
        isEditable: false,
        isAssignable: true,
        isArchived: false,
        permissionCount: 2,
        createdAt: 1,
        updatedAt: 1,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useRoleDetail: (id?: string) => ({
    data: id === 'system.platform.admin'
      ? systemPlatformAdminRoleDetail
      : id === 'custom.engine.secret-reader'
      ? {
        id: 'custom.engine.secret-reader',
        key: 'custom.engine.secret-reader',
        name: 'Custom Secret Reader',
        description: 'Secret reader',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        permissions: ['engine:secrets:view'],
        createdAt: 1,
        updatedAt: 1,
      }
      : id === 'custom.engine.audit-reader'
      ? {
        id: 'custom.engine.audit-reader',
        key: 'custom.engine.audit-reader',
        name: 'Custom Audit Reader',
        description: 'Unredacted audit reader',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        permissions: ['platform:audit:unredacted-view'],
        createdAt: 1,
        updatedAt: 1,
      }
      : id === 'custom.engine.permanent-delete'
      ? {
        id: 'custom.engine.permanent-delete',
        key: 'custom.engine.permanent-delete',
        name: 'Custom Permanent Delete',
        description: 'Permanent delete authority',
        scope: 'engine',
        kind: 'custom',
        isEditable: true,
        isAssignable: true,
        isArchived: false,
        permissionCount: 1,
        permissions: ['platform:users:permanent-delete'],
        createdAt: 1,
        updatedAt: 1,
      }
      : null,
    isLoading: false,
  }),
  useRoleAssignments: () => ({
    data: [
      {
        id: 'assignment-1',
        userId: '00000000-0000-4000-8000-000000000001',
        principalType: 'user',
        principalId: '00000000-0000-4000-8000-000000000001',
        roleId: 'custom.engine.operator',
        roleName: 'Custom Operator',
        roleScope: 'engine',
        resourceType: 'engine',
        resourceId: 'engine-1',
        scopeType: 'engine',
        scopeId: 'engine-1',
        source: 'manual',
        sourceMappingId: null,
        sourceRef: null,
        expiresAt: null,
        lastSeenAt: null,
        createdById: 'admin-1',
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'assignment-stale',
        userId: '00000000-0000-4000-8000-000000000030',
        principalType: 'user',
        principalId: '00000000-0000-4000-8000-000000000030',
        roleId: 'system.engine.deployer',
        roleName: 'Engine Deployer',
        roleScope: 'engine',
        resourceType: 'engine',
        resourceId: 'engine-1',
        scopeType: 'engine',
        scopeId: 'engine-1',
        source: 'sso',
        sourceMappingId: 'mapping-deleted',
        sourceRef: null,
        expiresAt: null,
        lastSeenAt: 1000,
        createdById: null,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'assignment-sso-1',
        userId: '00000000-0000-4000-8000-000000000012',
        principalType: 'user',
        principalId: '00000000-0000-4000-8000-000000000012',
        roleId: 'system.engine.operator',
        roleName: 'Engine Operator',
        roleScope: 'engine',
        resourceType: 'engine',
        resourceId: 'engine-1',
        scopeType: 'engine',
        scopeId: 'engine-1',
        source: 'sso',
        sourceMappingId: 'mapping-1',
        sourceRef: 'sso_assignment:mapping-1',
        expiresAt: null,
        lastSeenAt: 1000,
        createdById: null,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'assignment-engine-set-1',
        userId: '',
        principalType: 'group',
        principalId: 'group-1',
        roleId: 'system.engine.operator',
        roleName: 'Engine Operator',
        roleScope: 'engine',
        resourceType: 'engine_set',
        resourceId: 'engine-set-1',
        scopeType: 'engine_set',
        scopeId: 'engine-set-1',
        source: 'manual',
        sourceMappingId: null,
        sourceRef: null,
        expiresAt: null,
        lastSeenAt: null,
        createdById: 'admin-1',
        createdAt: 1000,
        updatedAt: 1000,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useAuthzGroups: () => ({
    data: [
      {
        id: 'group-1',
        tenantId: null,
        key: 'operations',
        name: 'Operations',
        description: null,
        source: 'manual',
        sourceRef: null,
        isSystem: false,
        isArchived: false,
        createdById: 'admin-1',
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'group-2',
        tenantId: null,
        key: 'sso-ops',
        name: 'SSO Operators',
        description: 'Synced from SSO',
        source: 'sso',
        sourceRef: 'mapping-1',
        isSystem: false,
        isArchived: false,
        createdById: null,
        createdAt: 1,
        updatedAt: 1,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useAuthzGroupMemberships: () => ({
    data: [
      {
        id: 'membership-1',
        tenantId: null,
        groupId: 'group-1',
        groupKey: 'operations',
        groupName: 'Operations',
        userId: '00000000-0000-4000-8000-000000000010',
        source: 'manual',
        sourceRef: null,
        expiresAt: null,
        createdById: 'admin-1',
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'membership-2',
        tenantId: null,
        groupId: 'group-2',
        groupKey: 'sso-ops',
        groupName: 'SSO Operators',
        userId: '00000000-0000-4000-8000-000000000011',
        source: 'sso',
        sourceRef: 'mapping-1',
        expiresAt: null,
        createdById: null,
        createdAt: 1,
        updatedAt: 1,
      },
    ] as AuthzGroupMembership[],
    isLoading: false,
    isError: false,
  }),
  useApiClients: () => ({
    data: [
      {
        id: 'client-1',
        name: 'Engine registration',
        tokenPrefix: 'egac_client',
        scopes: ['engine:register'],
        isActive: true,
        createdById: 'admin-1',
        lastUsedAt: null,
        revokedAt: null,
        createdAt: 1,
        updatedAt: 1,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useServiceAccounts: () => ({
    data: [
      {
        id: 'service-account-1',
        name: 'CI deployer',
        tokenPrefix: 'egsa_service',
        scopes: ['deployment:execute'],
        description: 'Deploys from CI',
        isActive: true,
        createdById: 'admin-1',
        lastUsedAt: null,
        revokedAt: null,
        createdAt: 1,
        updatedAt: 1,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useExternalEngineSystems: () => ({
    data: [
      {
        id: 'system-1',
        tenantId: null,
        key: 'fleet-manager',
        name: 'Fleet Manager',
        description: 'External CMDB',
        defaultManagementMode: 'hybrid',
        defaultFieldOwnership: { connection: 'external', auth: 'external', display: 'manual' },
        isActive: true,
        createdById: 'admin-1',
        createdAt: 900,
        updatedAt: 1000,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useExternalEngines: () => ({
    data: [
      {
        id: 'engine-1',
        name: 'External Engine',
        baseUrl: 'https://engine.example.com',
        type: 'camunda8',
        externalId: 'cluster-a/prod',
        labels: { environment: 'prod', region: 'eu' },
        registrationSource: 'external_api',
        externalSystemId: 'system-1',
        externalSystemName: 'Fleet Manager',
        managementMode: 'hybrid',
        fieldOwnership: { connection: 'external', auth: 'external', display: 'manual' },
        driftStatus: 'in_sync',
        lifecycleStatus: 'active',
        lastExternalSyncAt: 1200,
        capabilities: { operations: ['engine.read'] },
        capabilityStatus: 'mismatch',
        capabilityDiagnostics: {
          status: 'mismatch',
          expectedOperations: ['engine.read', 'engine.deploy', 'engine.instance.mutate'],
          reportedOperations: ['engine.read'],
          missingOperations: ['engine.deploy', 'engine.instance.mutate'],
          extraOperations: [],
          expectedSupportLevel: 'compatible',
          reportedSupportLevel: null,
          expectedCompatibilityProfile: 'camunda7-rest',
          reportedCompatibilityProfile: null,
          issues: ['Missing expected operations: engine.deploy, engine.instance.mutate.'],
          recommendation: 'Update the external registration payload to report the missing operations, then run reconcile again.',
        },
        externalUpdatedAt: 1000,
        createdAt: 900,
        updatedAt: 1000,
      },
      {
        id: 'engine-2',
        name: 'Decommissioned Engine',
        baseUrl: 'https://engine-2.example.com',
        type: 'camunda8',
        externalId: 'cluster-a/old',
        labels: { environment: 'old' },
        registrationSource: 'external_api',
        externalSystemId: 'system-1',
        externalSystemName: 'Fleet Manager',
        managementMode: 'external_managed',
        fieldOwnership: { connection: 'external', auth: 'external', display: 'external' },
        driftStatus: 'decommissioned',
        lifecycleStatus: 'decommissioned',
        lastExternalSyncAt: 1100,
        capabilities: { operations: ['engine.read'] },
        capabilityStatus: 'unknown',
        capabilityDiagnostics: {
          status: 'unknown',
          expectedOperations: ['engine.read', 'engine.deploy'],
          reportedOperations: [],
          missingOperations: ['engine.read', 'engine.deploy'],
          extraOperations: [],
          expectedSupportLevel: 'compatible',
          reportedSupportLevel: null,
          expectedCompatibilityProfile: 'camunda7-rest',
          reportedCompatibilityProfile: null,
          issues: ['No operation capabilities were reported by the external system.'],
          recommendation: 'Update the external registration payload to report the missing operations, then run reconcile again.',
        },
        externalUpdatedAt: 1000,
        createdAt: 800,
        updatedAt: 1100,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useExternalEngineAudit: () => ({
    data: [
      {
        id: 'audit-1',
        userId: 'admin-1',
        action: 'engine.external_registration.update',
        resourceType: 'engine',
        resourceId: 'engine-1',
        ipAddress: '127.0.0.1',
        userAgent: 'vitest',
        details: { externalId: 'cluster-a/prod', labels: { environment: 'prod' } },
        createdAt: 1000,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useAuthzAuditLog: (params?: { resourceType?: string; resourceId?: string }) => {
    const entries = [
      {
        id: 'authz-audit-1',
        userId: '00000000-0000-4000-8000-000000000021',
        action: 'platform.authz.roles.read',
        resourceType: 'platform',
        resourceId: null,
        decision: 'allow',
        reason: 'Allowed by role assignment',
        policyId: null,
        context: '{"roles":["system.platform.admin"],"sources":["manual"]}',
        ipAddress: '127.0.0.1',
        userAgent: 'vitest',
        timestamp: 1200,
      },
      {
        id: 'authz-audit-2',
        userId: '00000000-0000-4000-8000-000000000022',
        action: 'engine.instances.mutate',
        resourceType: 'engine',
        resourceId: 'engine-1',
        decision: 'deny',
        reason: 'Missing permission engine:process:modify',
        policyId: 'policy-1',
        context: '{"checks":["basePermission"],"sources":[]}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1100,
      },
      {
        id: 'authz-audit-engine-set-1',
        userId: '00000000-0000-4000-8000-000000000031',
        action: 'engine.deploy.create',
        resourceType: 'engine_set',
        resourceId: 'engine-set-1',
        decision: 'allow',
        reason: 'Allowed by Engine Set assignment',
        policyId: null,
        context: '{"engineSetId":"engine-set-1"}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1300,
      },
      {
        id: 'authz-audit-assignment-1',
        userId: 'admin-1',
        action: 'authz.role_assignment.create',
        resourceType: 'role_assignment',
        resourceId: 'assignment-1',
        decision: 'allow',
        reason: 'Role assignment created',
        policyId: null,
        context: '{"assignmentId":"assignment-1","principalId":"00000000-0000-4000-8000-000000000001","roleId":"custom.engine.operator"}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1400,
      },
      {
        id: 'authz-audit-sso-assignment-1',
        userId: '00000000-0000-4000-8000-000000000012',
        action: 'authz.sso_assignment.create',
        resourceType: 'role_assignment',
        resourceId: 'assignment-sso-1',
        decision: 'allow',
        reason: 'SSO assignment created',
        policyId: null,
        context: '{"assignmentId":"assignment-sso-1","sourceMappingId":"mapping-1","mappingId":"mapping-1"}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1500,
      },
      {
        id: 'authz-audit-sso-group-membership-1',
        userId: '00000000-0000-4000-8000-000000000011',
        action: 'authz.sso_group_membership.create',
        resourceType: 'authz_group_membership',
        resourceId: 'membership-2',
        decision: 'allow',
        reason: 'SSO group membership created',
        policyId: null,
        context: '{"membershipId":"membership-2","groupId":"group-2","sourceRef":"mapping-1"}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1600,
      },
      {
        id: 'authz-audit-api-client-1',
        userId: 'admin-1',
        action: 'platform.api_client.rotate',
        resourceType: 'api_client',
        resourceId: 'client-1',
        decision: 'allow',
        reason: 'API client token rotated',
        policyId: null,
        context: '{"apiClientId":"client-1"}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1700,
      },
      {
        id: 'authz-audit-service-account-1',
        userId: 'admin-1',
        action: 'authz.role_assignment.create',
        resourceType: 'role_assignment',
        resourceId: 'assignment-service-account-1',
        decision: 'allow',
        reason: 'Service account role assignment created',
        policyId: null,
        context: '{"assignmentId":"assignment-service-account-1","principalType":"service_account","principalId":"service-account-1"}',
        ipAddress: null,
        userAgent: null,
        timestamp: 1650,
      },
    ] as AuthzAuditEntry[];
    return {
      data: entries.filter((entry) => {
        if (params?.resourceType && entry.resourceType !== params.resourceType) return false;
        if (params?.resourceId && entry.resourceId !== params.resourceId) return false;
        return true;
      }),
      isLoading: false,
      isError: false,
    };
  },
  useEngineSets: () => ({
    data: [
      {
        id: 'engine-set-1',
        tenantId: null,
        key: 'prod-engines',
        name: 'Production Engines',
        description: 'Production estate',
        selector: { mode: 'labels', labels: { environment: 'prod' }, labelMatch: 'all' },
        selectorFingerprint: 'fingerprint-1',
        source: 'manual',
        sourceRef: null,
        isArchived: false,
        createdById: 'admin-1',
        lastMaterializedAt: 1200,
        materializationStatus: 'ok',
        materializationError: null,
        materializedEngineCount: 1,
        createdAt: 900,
        updatedAt: 1200,
      },
    ] as EngineSetSummary[],
    isLoading: false,
    isError: false,
  }),
  useEngineSet: (id?: string) => ({
    data: id === 'engine-set-1'
      ? {
        id: 'engine-set-1',
        tenantId: null,
        key: 'prod-engines',
        name: 'Production Engines',
        description: 'Production estate',
        selector: { mode: 'labels', labels: { environment: 'prod' }, labelMatch: 'all' },
        selectorFingerprint: 'fingerprint-1',
        source: 'manual',
        sourceRef: null,
        isArchived: false,
        createdById: 'admin-1',
        lastMaterializedAt: 1200,
        materializationStatus: 'ok',
        materializationError: null,
        materializedEngineCount: 1,
        createdAt: 900,
        updatedAt: 1200,
        materializations: [
          {
            id: 'materialization-1',
            tenantId: null,
            engineSetId: 'engine-set-1',
            engineId: 'engine-1',
            engineName: 'External Engine',
            selectorFingerprint: 'fingerprint-1',
            matchedBy: { label: 'environment=prod' },
            lineage: { source: 'manual' },
            source: 'manual',
            sourceRef: null,
            lastSeenAt: 1200,
            createdAt: 1000,
            updatedAt: 1200,
          },
        ],
      }
      : null,
    isLoading: false,
  }),
  useProjectEngineTargets: () => ({
    data: [
      {
        id: 'target-1',
        tenantId: null,
        projectId: 'project-1',
        projectName: 'Payments',
        engineId: 'engine-1',
        engineName: 'External Engine',
        engineBaseUrl: 'https://engine.example.com',
        environment: { id: 'prod', name: 'Production', color: '#0f62fe', manualDeployAllowed: true },
        status: 'active',
        source: 'manual',
        sourceRef: null,
        externalSystemId: null,
        externalProjectId: null,
        externalEngineId: null,
        externalTargetId: null,
        allowManualDeploy: true,
        allowCiDeploy: true,
        allowApiDeploy: false,
        allowImport: false,
        createdById: 'admin-1',
        approvedById: null,
        approvalStatus: 'not_required',
        approvedAt: null,
        policyTags: ['prod'],
        diagnostics: { health: 'ok' },
        lastSeenAt: 1200,
        createdAt: 900,
        updatedAt: 1200,
      },
      {
        id: 'target-2',
        tenantId: null,
        projectId: 'project-2',
        projectName: 'Inventory',
        engineId: 'engine-2',
        engineName: 'Decommissioned Engine',
        engineBaseUrl: 'https://engine-2.example.com',
        environment: null,
        status: 'active',
        source: 'external',
        sourceRef: 'cmdb-target-2',
        externalSystemId: 'system-1',
        externalProjectId: 'cmdb-project-2',
        externalEngineId: 'cluster-a/old',
        externalTargetId: 'cmdb-target-2',
        allowManualDeploy: false,
        allowCiDeploy: false,
        allowApiDeploy: true,
        allowImport: true,
        createdById: null,
        approvedById: null,
        approvalStatus: 'approved',
        approvedAt: 1100,
        policyTags: ['external'],
        diagnostics: { source: 'cmdb' },
        lastSeenAt: 1200,
        createdAt: 900,
        updatedAt: 1200,
      },
    ] as ProjectEngineTarget[],
    isLoading: false,
    isError: false,
  }),
  useSsoClaimsMappings: () => ({
    data: [
      {
        id: 'platform-mapping-1',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'Platform Admins',
        targetRole: 'admin',
        priority: 10,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
    ] as SsoClaimsMapping[],
    isLoading: false,
    isError: false,
  }),
  useSsoGroupMappings: () => ({
    data: [
      {
        id: 'group-mapping-1',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'Operators',
        targetGroupId: 'group-1',
        targetGroupKey: 'operations',
        targetGroupName: 'Operations',
        syncMode: 'authoritative',
        priority: 5,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-1',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'SSO Operators',
        targetGroupId: 'group-2',
        targetGroupKey: 'sso-ops',
        targetGroupName: 'SSO Operators',
        syncMode: 'authoritative',
        priority: 6,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
    ] as SsoGroupMapping[],
    isLoading: false,
    isError: false,
  }),
  useSsoAssignmentMappings: () => ({
    data: [
      {
        id: 'mapping-1',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'Ops',
        targetScope: 'engine',
        targetSelectorType: 'external_engine_id',
        targetEngineId: null,
        targetExternalEngineId: 'cluster-a/prod',
        targetLabelKey: null,
        targetLabelValue: null,
        targetRoleId: 'system.engine.operator',
        syncMode: 'authoritative',
        priority: 0,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-2',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'All Engines',
        targetScope: 'engine',
        targetSelectorType: 'all_engines',
        targetEngineId: null,
        targetExternalEngineId: null,
        targetLabelKey: null,
        targetLabelValue: null,
        targetRoleId: 'system.engine.deployer',
        syncMode: 'additive',
        priority: 1,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-3',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'QA',
        targetScope: 'engine',
        targetSelectorType: 'engine_label',
        targetEngineId: null,
        targetExternalEngineId: null,
        targetLabelKey: 'environment',
        targetLabelValue: 'qa',
        targetRoleId: 'system.engine.operator',
        syncMode: 'authoritative',
        priority: 2,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-4',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: '^Regex Ops$',
        claimOperator: 'matches_regex',
        targetScope: 'engine',
        targetSelectorType: 'engine_id',
        targetEngineId: 'engine-1',
        targetExternalEngineId: null,
        targetLabelKey: null,
        targetLabelValue: null,
        targetRoleId: 'system.engine.operator',
        syncMode: 'authoritative',
        priority: 3,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-5',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'Secret Readers',
        targetScope: 'engine',
        targetSelectorType: 'engine_id',
        targetEngineId: 'engine-1',
        targetExternalEngineId: null,
        targetLabelKey: null,
        targetLabelValue: null,
        targetRoleId: 'custom.engine.secret-reader',
        syncMode: 'authoritative',
        priority: 4,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-6',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'Audit Readers',
        targetScope: 'engine',
        targetSelectorType: 'engine_id',
        targetEngineId: 'engine-1',
        targetExternalEngineId: null,
        targetLabelKey: null,
        targetLabelValue: null,
        targetRoleId: 'custom.engine.audit-reader',
        syncMode: 'authoritative',
        priority: 5,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
      {
        id: 'mapping-7',
        providerId: null,
        claimType: 'group',
        claimKey: 'groups',
        claimValue: 'Delete Operators',
        targetScope: 'engine',
        targetSelectorType: 'engine_id',
        targetEngineId: 'engine-1',
        targetExternalEngineId: null,
        targetLabelKey: null,
        targetLabelValue: null,
        targetRoleId: 'custom.engine.permanent-delete',
        syncMode: 'authoritative',
        priority: 6,
        isActive: true,
        createdAt: 1,
        updatedAt: 1,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useSsoSyncRuns: () => ({
    data: [
      {
        id: 'sync-run-1',
        tenantId: null,
        providerId: 'microsoft',
        userId: '00000000-0000-4000-8000-000000000020',
        trigger: 'login',
        status: 'failed',
        startedAt: 1200,
        completedAt: 1500,
        groupMembershipsCreated: 1,
        groupMembershipsUpdated: 0,
        groupMembershipsRemoved: 0,
        assignmentsCreated: 1,
        assignmentsUpdated: 0,
        assignmentsRemoved: 0,
        errorCode: 'sync_failed',
        errorMessage: 'Engine materialization failed',
        details: '{"providerType":"microsoft"}',
      },
    ] as SsoSyncRun[],
    isLoading: false,
    isError: false,
  }),
  useSsoSyncEvents: (runId?: string) => ({
    data: runId === 'sync-run-1'
      ? [
        {
          id: 'sync-event-1',
          tenantId: null,
          providerId: 'microsoft',
          runId: 'sync-run-1',
          severity: 'error',
          type: 'engine_assignment.materialization_failed',
          userId: '00000000-0000-4000-8000-000000000020',
          mappingType: 'sso_assignment',
          mappingId: 'mapping-1',
          resourceType: 'engine',
          resourceId: 'engine-1',
          message: 'Engine materialization failed',
          details: '{"engineId":"engine-1"}',
          createdAt: 1400,
        },
      ] as SsoSyncEvent[]
      : [],
    isLoading: false,
    isError: false,
  }),
  useRunSsoSyncDiagnostics: () => ({
    mutateAsync: runSsoSyncDiagnostics,
    isPending: false,
    data: {
      runId: 'sync-run-2',
      scannedGroupMappings: 1,
      scannedAssignmentMappings: 3,
      scannedGroupMemberships: 2,
      scannedAssignments: 2,
      warnings: 1,
      errors: 0,
    },
  }),
  useAuthzPolicies: () => ({
    data: [
      {
        id: 'policy-1',
        name: 'Block production deploys outside hours',
        description: 'Production deployment guardrail',
        effect: 'deny',
        priority: 100,
        resourceType: 'engine',
        action: 'engine:deploy',
        conditions: {
          timeWindow: {
            start: '17:00',
            end: '09:00',
            timezone: 'UTC',
          },
        },
        isActive: true,
      },
      {
        id: 'policy-2',
        name: 'Inactive allow policy',
        effect: 'allow',
        priority: 10,
        resourceType: undefined,
        action: undefined,
        conditions: {},
        isActive: false,
      },
    ] as AuthzPolicy[],
    isLoading: false,
    isError: false,
  }),
  useCreateCustomRole: () => ({ mutateAsync: createRole, isPending: false }),
  useCreateCustomPermission: () => ({ mutateAsync: createPermission, isPending: false }),
  useCreateAuthzGroup: () => ({ mutateAsync: createGroup, isPending: false }),
  useUpdateAuthzGroup: () => ({ mutateAsync: updateGroup, isPending: false }),
  useDeleteAuthzGroup: () => ({ mutateAsync: archiveGroup, isPending: false }),
  useAddAuthzGroupMembership: () => ({ mutateAsync: addGroupMembership, isPending: false }),
  useRemoveAuthzGroupMembership: () => ({ mutateAsync: removeGroupMembership, isPending: false }),
  useUpdateCustomRole: () => ({ mutateAsync: updateRole, isPending: false }),
  useArchiveCustomRole: () => ({ mutateAsync: archiveRole, isPending: false }),
  useAssignRole: () => ({ mutateAsync: assignRole, isPending: false }),
  useRemoveRoleAssignment: () => ({ mutateAsync: removeAssignment, isPending: false }),
  useCreateEngineSet: () => ({ mutateAsync: createEngineSet, isPending: false }),
  useUpdateEngineSet: () => ({ mutateAsync: updateEngineSet, isPending: false }),
  useArchiveEngineSet: () => ({ mutateAsync: archiveEngineSet, isPending: false }),
  usePreviewEngineSetSelector: () => ({
    mutateAsync: previewEngineSetSelector,
    reset: resetPreviewEngineSetSelector,
    isPending: false,
    data: {
      selector: { mode: 'labels', labels: { environment: 'prod' }, labelMatch: 'all' },
      selectorFingerprint: 'fingerprint-preview',
      riskReasons: [],
      warnings: [],
      matchedEngines: [
        {
          engineId: 'engine-1',
          engineName: 'External Engine',
          labels: { environment: 'prod' },
          matchedBy: { label: 'environment=prod' },
        },
      ],
    },
  }),
  useMaterializeEngineSet: () => ({ mutateAsync: materializeEngineSet, isPending: false }),
  useCreateProjectEngineTarget: () => ({ mutateAsync: createProjectEngineTarget, isPending: false }),
  useUpdateProjectEngineTarget: () => ({ mutateAsync: updateProjectEngineTarget, isPending: false }),
  useArchiveProjectEngineTarget: () => ({ mutateAsync: archiveProjectEngineTarget, isPending: false }),
  useSyncLegacyProjectEngineTargets: () => ({ mutateAsync: syncLegacyProjectEngineTargets, isPending: false }),
  useEvaluateDeploymentEligibility: () => ({ mutateAsync: evaluateDeploymentEligibility, isPending: false }),
  useCreatePolicy: () => ({ mutateAsync: createPolicy, isPending: false }),
  useUpdatePolicy: () => ({ mutateAsync: updatePolicy, isPending: false }),
  useDeletePolicy: () => ({ mutateAsync: deletePolicy, isPending: false }),
  useCreateApiClient: () => ({ mutateAsync: createApiClient, isPending: false }),
  useRotateApiClient: () => ({ mutateAsync: rotateApiClient, isPending: false }),
  useRevokeApiClient: () => ({ mutateAsync: revokeApiClient, isPending: false }),
  useCreateServiceAccount: () => ({ mutateAsync: createServiceAccount, isPending: false }),
  useRotateServiceAccount: () => ({ mutateAsync: rotateServiceAccount, isPending: false }),
  useRevokeServiceAccount: () => ({ mutateAsync: revokeServiceAccount, isPending: false }),
  useCreateExternalEngineSystem: () => ({ mutateAsync: createExternalSystem, isPending: false }),
  useUpdateExternalEngineSystem: () => ({ mutateAsync: updateExternalSystem, isPending: false }),
  useArchiveExternalEngineSystem: () => ({ mutateAsync: archiveExternalSystem, isPending: false }),
  useDecommissionExternalEngine: () => ({ mutateAsync: decommissionExternalEngine, isPending: false }),
  useReactivateExternalEngine: () => ({ mutateAsync: reactivateExternalEngine, isPending: false }),
  useReconcileExternalEngine: () => ({ mutateAsync: reconcileExternalEngine, isPending: false }),
  useCreateSsoMapping: () => ({ mutateAsync: createSsoPlatformMapping, isPending: false }),
  useUpdateSsoMapping: () => ({ mutateAsync: updateSsoPlatformMapping, isPending: false }),
  useDeleteSsoMapping: () => ({ mutateAsync: deleteSsoPlatformMapping, isPending: false }),
  useTestSsoMapping: () => ({
    mutateAsync: testSsoPlatformMapping,
    isPending: false,
    data: { resolvedRole: 'admin', matchedMappings: [{ id: 'platform-mapping-1', name: 'Platform Admins', targetRole: 'admin' }] },
  }),
  useCreateSsoGroupMapping: () => ({ mutateAsync: createSsoGroupMapping, isPending: false }),
  useUpdateSsoGroupMapping: () => ({ mutateAsync: updateSsoGroupMapping, isPending: false }),
  useDeleteSsoGroupMapping: () => ({ mutateAsync: deleteSsoGroupMapping, isPending: false }),
  useTestSsoGroupMapping: () => ({
    mutateAsync: testSsoGroupMapping,
    isPending: false,
    data: {
      matchedMappings: [
        {
          id: 'group-mapping-1',
          providerId: null,
          claimType: 'group',
          claimKey: 'groups',
          claimValue: 'Operators',
          targetGroupId: 'group-1',
          targetGroupKey: 'operations',
          targetGroupName: 'Operations',
          syncMode: 'authoritative',
          priority: 5,
          isActive: true,
          createdAt: 1,
          updatedAt: 1,
        },
      ],
      memberships: [{ groupId: 'group-1', mappingId: 'group-mapping-1' }],
    },
  }),
  useCreateSsoAssignmentMapping: () => ({ mutateAsync: createSsoAssignment, isPending: false }),
  useUpdateSsoAssignmentMapping: () => ({ mutateAsync: updateSsoAssignment, isPending: false }),
  useDeleteSsoAssignmentMapping: () => ({ mutate: deleteSsoAssignment, isPending: false }),
  useTestSsoAssignmentMapping: () => ({ mutateAsync: testSsoAssignment, isPending: false, data: ssoAssignmentTestState.data }),
  useSsoEngineAccessSnapshots: () => ({
    data: [
      {
        id: 'snapshot-1',
        tenantId: null,
        providerId: 'microsoft',
        mappingId: 'mapping-1',
        principalType: 'user',
        principalId: 'user-1',
        engineId: 'engine-1',
        providerSubjectIds: ['subject-1'],
        providerGroupIds: ['group-1'],
        providerAppRoleIds: [],
        currentRoleIds: ['system.engine.operator'],
        previousRoleIds: ['system.engine.deployer'],
        status: 'active',
        cleanupReason: null,
        lastSeenAt: 1000,
        lastSyncedAt: 1000,
        removedAt: null,
        details: { source: 'sso' },
        createdAt: 900,
        updatedAt: 1000,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  usePreviewEngineAccessTransitionCleanup: () => ({
    mutateAsync: previewEngineAccessTransitionCleanup,
    isPending: false,
    error: null,
    data: {
      previewCorrelationId: 'preview-1',
      engineId: 'engine-1',
      candidates: [
        {
          manualAssignmentId: 'manual-1',
          ssoAssignmentId: 'sso-1',
          principalType: 'user',
          principalId: 'user-1',
          engineId: 'engine-1',
          manualRoleId: 'system.engine.operator',
          ssoRoleId: 'system.engine.operator',
          sourceMappingId: 'mapping-1',
          lastSnapshotStatus: 'active',
          recommendedAction: 'remove_manual_duplicate',
        },
      ],
    },
  }),
  useApplyEngineAccessTransitionCleanup: () => ({
    mutateAsync: applyEngineAccessTransitionCleanup,
    isPending: false,
    error: null,
  }),
  useEvaluateAccess: () => ({ mutateAsync: evaluateAccess, isPending: false, isError: false, data: evaluateAccessState.data }),
}));

vi.mock('@src/features/platform-admin/hooks/usePlatformSyncSettings', () => ({
  usePlatformSyncSettings: () => ({
    data: {
      syncPushEnabled: true,
      syncPullEnabled: false,
      gitProjectTokenSharingEnabled: false,
      defaultDeployRoles: ['owner', 'delegate', 'operator'],
      engineOnboardingMode: 'manual_allowed',
      projectEngineTargetMode: 'manual_allowed',
      ssoAllEnginesAssignmentMappingsEnabled: true,
      ssoEngineOwnerAssignmentMappingsEnabled: false,
      ssoEngineDelegateAssignmentMappingsEnabled: false,
      ssoRegexClaimMappingsEnabled: true,
      ssoSecretViewMappingsEnabled: false,
      ssoUnredactedAuditMappingsEnabled: false,
      ssoPermanentDeleteMappingsEnabled: false,
    },
    isLoading: false,
  }),
}));

vi.mock('@src/shared/hooks/useAuth', () => ({
  useAuth: () => authState,
}));


export function resetAccessControlMocks() {
    vi.clearAllMocks();
    ssoAssignmentTestState.data = null;
    evaluateAccessState.data = null;
    runSsoSyncDiagnostics.mockResolvedValue({
      runId: 'sync-run-2',
      scannedGroupMappings: 1,
      scannedAssignmentMappings: 3,
      scannedGroupMemberships: 2,
      scannedAssignments: 2,
      warnings: 1,
      errors: 0,
    });
    createGroup.mockResolvedValue({ id: 'group-new' });
    updateGroup.mockResolvedValue({ success: true });
    archiveGroup.mockResolvedValue(undefined);
    addGroupMembership.mockResolvedValue({ id: 'membership-new' });
    removeGroupMembership.mockResolvedValue(undefined);
    createEngineSet.mockResolvedValue({ id: 'engine-set-new' });
    updateEngineSet.mockResolvedValue({ success: true });
    archiveEngineSet.mockResolvedValue(undefined);
    previewEngineSetSelector.mockResolvedValue({
      selector: { mode: 'labels', labels: { environment: 'prod' }, labelMatch: 'all' },
      selectorFingerprint: 'fingerprint-preview',
      riskReasons: [],
      warnings: [],
      matchedEngines: [
        {
          engineId: 'engine-1',
          engineName: 'External Engine',
          labels: { environment: 'prod' },
          matchedBy: { label: 'environment=prod' },
        },
      ],
    });
    materializeEngineSet.mockResolvedValue({
      engineSetId: 'engine-set-1',
      selectorFingerprint: 'fingerprint-1',
      matched: 1,
      created: 0,
      updated: 1,
      removed: 0,
      materializations: [],
    });
    createProjectEngineTarget.mockResolvedValue({ id: 'target-new' });
    updateProjectEngineTarget.mockResolvedValue({ success: true });
    archiveProjectEngineTarget.mockResolvedValue(undefined);
    syncLegacyProjectEngineTargets.mockResolvedValue({ createdOrUpdated: 2 });
    createPolicy.mockResolvedValue({ id: 'policy-new' });
    updatePolicy.mockResolvedValue(undefined);
    deletePolicy.mockResolvedValue(undefined);
    evaluateDeploymentEligibility.mockResolvedValue({
      allowed: false,
      decision: 'deny',
      mode: 'manual',
      projectId: 'project-1',
      engineId: 'engine-1',
      checks: [
        { id: 'target.active', allowed: true, reason: 'Target is active' },
        { id: 'engine.permission', allowed: false, reason: 'Missing engine deploy permission' },
      ],
      reasons: ['Missing engine deploy permission'],
    });
    reconcileExternalEngine.mockResolvedValue({
      engineId: 'engine-1',
      externalId: 'cluster-a/prod',
      lifecycleStatus: 'active',
      capabilityStatus: 'mismatch',
      capabilityDiagnostics: {
        status: 'mismatch',
        expectedOperations: ['engine.read', 'engine.deploy', 'engine.instance.mutate'],
        reportedOperations: ['engine.read'],
        missingOperations: ['engine.deploy', 'engine.instance.mutate'],
        extraOperations: [],
        expectedSupportLevel: 'compatible',
        reportedSupportLevel: null,
        expectedCompatibilityProfile: 'camunda7-rest',
        reportedCompatibilityProfile: null,
        issues: ['Missing expected operations: engine.deploy, engine.instance.mutate.'],
        recommendation: 'Update the external registration payload to report the missing operations, then run reconcile again.',
      },
      materializationResults: [],
      materializationDiagnostics: {
        engineSetCount: 1,
        matched: 1,
        created: 0,
        updated: 1,
        removed: 0,
        errors: [],
        status: 'ok',
        summary: '1 Engine Set checked; 0 created, 1 updated, 0 removed',
      },
    });
    createSsoPlatformMapping.mockResolvedValue({ id: 'platform-mapping-new' });
    updateSsoPlatformMapping.mockResolvedValue(undefined);
    deleteSsoPlatformMapping.mockResolvedValue(undefined);
    testSsoPlatformMapping.mockResolvedValue({ resolvedRole: 'admin', matchedMappings: [{ id: 'platform-mapping-1', name: 'Platform Admins', targetRole: 'admin' }] });
    createSsoGroupMapping.mockResolvedValue({ id: 'group-mapping-new' });
    updateSsoGroupMapping.mockResolvedValue(undefined);
    deleteSsoGroupMapping.mockResolvedValue(undefined);
    testSsoGroupMapping.mockResolvedValue({ matchedMappings: [], memberships: [] });
    previewEngineAccessTransitionCleanup.mockResolvedValue({
      previewCorrelationId: 'preview-1',
      engineId: 'engine-1',
      candidates: [
        {
          manualAssignmentId: 'manual-1',
          ssoAssignmentId: 'sso-1',
          principalType: 'user',
          principalId: 'user-1',
          engineId: 'engine-1',
          manualRoleId: 'system.engine.operator',
          ssoRoleId: 'system.engine.operator',
          sourceMappingId: 'mapping-1',
          lastSnapshotStatus: 'active',
          recommendedAction: 'remove_manual_duplicate',
        },
      ],
    });
    applyEngineAccessTransitionCleanup.mockResolvedValue({
      previewCorrelationId: 'preview-1',
      engineId: 'engine-1',
      removedAssignmentIds: ['manual-1'],
      removedCount: 1,
    });
    authState.permissions = {
      userId: 'admin-1',
      platform: [
        'platform:authz:roles:view',
        'platform:authz:roles:manage',
        'platform:authz:check',
        'platform:settings:manage',
        'platform:sso-assignments:view',
        'platform:sso-assignments:manage',
        'platform:engine-sets:view',
        'platform:engine-sets:manage',
        'platform:project-engine-targets:view',
        'platform:project-engine-targets:manage',
        'platform:engine-registration:manage',
        'platform:audit:view',
      ],
      projects: [],
      engines: [],
      generatedAt: 1,
    };
}

export {
  ssoAssignmentTestState,
  evaluateAccessState,
  authState,
  createRole,
  createPermission,
  createGroup,
  updateGroup,
  archiveGroup,
  addGroupMembership,
  removeGroupMembership,
  updateRole,
  archiveRole,
  assignRole,
  removeAssignment,
  createEngineSet,
  updateEngineSet,
  archiveEngineSet,
  previewEngineSetSelector,
  resetPreviewEngineSetSelector,
  materializeEngineSet,
  createProjectEngineTarget,
  updateProjectEngineTarget,
  archiveProjectEngineTarget,
  syncLegacyProjectEngineTargets,
  evaluateDeploymentEligibility,
  createPolicy,
  updatePolicy,
  deletePolicy,
  createApiClient,
  rotateApiClient,
  revokeApiClient,
  createServiceAccount,
  rotateServiceAccount,
  revokeServiceAccount,
  createExternalSystem,
  updateExternalSystem,
  archiveExternalSystem,
  decommissionExternalEngine,
  reactivateExternalEngine,
  reconcileExternalEngine,
  createSsoPlatformMapping,
  updateSsoPlatformMapping,
  deleteSsoPlatformMapping,
  testSsoPlatformMapping,
  createSsoGroupMapping,
  updateSsoGroupMapping,
  deleteSsoGroupMapping,
  testSsoGroupMapping,
  createSsoAssignment,
  updateSsoAssignment,
  deleteSsoAssignment,
  testSsoAssignment,
  runSsoSyncDiagnostics,
  previewEngineAccessTransitionCleanup,
  applyEngineAccessTransitionCleanup,
  evaluateAccess
};

export type {
  AuthzAuditEntry,
  AuthzGroup,
  AuthzGroupMembership,
  AuthzPolicy,
  EngineSetSummary,
  EffectiveAccessResult,
  ExternalEngineRegistration,
  PermissionCatalogEntry,
  ProjectEngineTarget,
  RoleAssignment,
  RoleSummary,
  SsoClaimsMapping,
  SsoGroupMapping,
  SsoAssignmentMapping,
  SsoSyncEvent,
  SsoSyncRun,
};
