apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/configmap.yaml
  - storage/backend-pvc.yaml
  - app/backend-deployment.yaml
  - app/backend-service.yaml
  - app/frontend-deployment.yaml
  - app/frontend-service.yaml
  - network/frontend-route.yaml
